/**
 * User-facing copy for the dsh-android cards and panel (en/zh, like the host).
 *
 * `AndroidCopy` is derived from the ENGLISH table, so a key missing from the
 * Chinese table is a compile error (the dsh-ios pattern, kept verbatim).
 * Every `err*` key maps 1:1 to an `AndroidRouteErrorCode` the host routes
 * report — see ROUTE_ERROR_COPY_KEYS in protocol.ts.
 */
export type AndroidLocale = 'en' | 'zh';
declare const COPY: {
    readonly en: {
        readonly android: "Android";
        readonly actionBoot: "Start";
        readonly actionScreenshot: "Screenshot";
        readonly actionInteract: "Interact";
        readonly actionBuildRun: "Build & Run";
        readonly booting: "Starting the device stream…";
        readonly connecting: "Connecting to the live stream…";
        readonly connectingScreenshot: "Loading screenshot…";
        readonly live: "live";
        readonly unavailable: "unavailable";
        readonly done: "done";
        readonly streamUnavailable: "stream not available";
        readonly screenshotUnavailable: "screenshot not available";
        readonly retry: "Retry";
        readonly refresh: "Refresh";
        readonly back: "Back";
        readonly home: "Home";
        readonly recents: "Recents";
        readonly deviceMenu: "Device actions";
        readonly deviceNotifications: "Notifications";
        readonly deviceQuickSettings: "Quick Settings";
        readonly deviceLock: "Lock screen";
        readonly deviceWake: "Wake";
        readonly deviceAssistant: "Assistant";
        readonly deviceActionFailed: "the device action failed";
        readonly screenshot: "Screenshot";
        readonly captured: "Captured";
        readonly capturing: "Capturing…";
        readonly rotate: "Rotate";
        readonly toolbar: "Device toolbar";
        readonly sizeMode: "Device display size";
        readonly frameStyle: "Device frame style";
        readonly frameStyleNone: "Frameless";
        readonly frameStyleBezel: "Bezel";
        readonly frameStyleDevice: "Phone frame";
        readonly sizeQuickFit: "Fit to panel width";
        readonly sizeQuickPercent100: "Display at 100%";
        readonly sizeQuickS: "Small size (S, 240px)";
        readonly sizeQuickM: "Medium size (M, 320px)";
        readonly streamAlt: "Live Android device — click to tap, drag to gesture";
        readonly screenshotAlt: "Android device screenshot";
        readonly captureScreenshot: "Capturing screenshot…";
        readonly interacting: "Interacting with the device…";
        readonly building: "Building and installing the app…";
        readonly noPreview: "No live view is available for this result.";
        readonly toolFailed: "The tool call failed.";
        readonly openApk: "Open APK";
        readonly openScreenshot: "Open screenshot";
        readonly packageName: "Package";
        readonly device: "device";
        readonly offline: "Offline";
        readonly panelLive: "Live";
        readonly closePanel: "Close device panel";
        readonly backgroundMode: "AI background";
        readonly backgroundModeHint: "Keep AI control available without opening the live panel";
        readonly resizePanel: "Drag to resize the device panel";
        readonly openInPanel: "Open in sidebar";
        readonly openAndroidPanel: "Open device panel";
        readonly devicePicker: "Android device";
        readonly deviceSwitching: "Switching…";
        readonly deviceStreaming: "live";
        readonly deviceOnline: "online";
        readonly deviceEmulators: "Emulators";
        readonly devicePhysical: "Phones";
        readonly deviceAvds: "Available AVDs";
        readonly deviceAvdHint: "start it with android_boot";
        readonly deviceNone: "No device connected";
        readonly followActive: "Auto-follow";
        readonly followHint: "The panel follows the agent’s newest target device";
        readonly followResume: "Resume following";
        readonly switchFailed: "Switch failed";
        readonly errForbidden: "the request was refused (loopback-trusted browsers only)";
        readonly errBadMethod: "the route refused this request method";
        readonly errBadContentType: "the route expects a JSON request";
        readonly errBadRequest: "the request was malformed";
        readonly errDeviceUnknown: "the device is not connected — run android_devices, or start an emulator with android_boot";
        readonly errDeviceOffline: "the device is not ready (adb reports it offline)";
        readonly errDeviceUnauthorized: "the device has not authorized this computer — allow USB debugging on the phone, then retry";
        readonly errDeviceBusy: "another device is streaming; pick it in the device list to switch";
        readonly errStreamNotRunning: "no stream is running for this device";
        readonly errStreamFailed: "the device stream failed to start";
        readonly errTokenInvalid: "the access link expired; refresh to get a new one";
        readonly errScreenshotMissing: "the screenshot file is gone";
        readonly errAdbUnavailable: "adb is unavailable on this host — install the Android platform tools";
        readonly errUnavailable: "the device is unavailable";
    };
    readonly zh: {
        readonly android: "Android 设备";
        readonly actionBoot: "启动";
        readonly actionScreenshot: "截图";
        readonly actionInteract: "交互";
        readonly actionBuildRun: "构建运行";
        readonly booting: "正在启动设备画面…";
        readonly connecting: "正在连接实时画面…";
        readonly connectingScreenshot: "正在加载截图…";
        readonly live: "实时";
        readonly unavailable: "不可用";
        readonly done: "完成";
        readonly streamUnavailable: "画面不可用";
        readonly screenshotUnavailable: "截图不可用";
        readonly retry: "重试";
        readonly refresh: "刷新";
        readonly back: "返回";
        readonly home: "主屏幕";
        readonly recents: "最近任务";
        readonly deviceMenu: "设备操作";
        readonly deviceNotifications: "通知栏";
        readonly deviceQuickSettings: "快捷设置";
        readonly deviceLock: "锁屏";
        readonly deviceWake: "唤醒";
        readonly deviceAssistant: "语音助手";
        readonly deviceActionFailed: "设备操作失败";
        readonly screenshot: "截图";
        readonly captured: "已截图";
        readonly capturing: "正在截图…";
        readonly rotate: "旋转";
        readonly toolbar: "设备工具栏";
        readonly sizeMode: "设备显示大小";
        readonly frameStyle: "设备边框样式";
        readonly frameStyleNone: "无框";
        readonly frameStyleBezel: "边框";
        readonly frameStyleDevice: "手机框";
        readonly sizeQuickFit: "适应面板宽度";
        readonly sizeQuickPercent100: "以 100% 显示";
        readonly sizeQuickS: "小尺寸（S，240px）";
        readonly sizeQuickM: "中尺寸（M，320px）";
        readonly streamAlt: "实时 Android 画面 — 点击轻触，拖动手势";
        readonly screenshotAlt: "Android 设备截图";
        readonly captureScreenshot: "正在截取屏幕…";
        readonly interacting: "正在与设备交互…";
        readonly building: "正在构建并安装应用…";
        readonly noPreview: "此结果没有可用的实时视图。";
        readonly toolFailed: "工具调用失败。";
        readonly openApk: "打开 APK";
        readonly openScreenshot: "打开截图";
        readonly packageName: "包名";
        readonly device: "设备";
        readonly offline: "离线";
        readonly panelLive: "实时";
        readonly closePanel: "关闭设备面板";
        readonly backgroundMode: "AI 后台";
        readonly backgroundModeHint: "不打开实时面板，AI 仍可在后台控制设备";
        readonly resizePanel: "拖动调整设备面板宽度";
        readonly openInPanel: "在侧边栏打开";
        readonly openAndroidPanel: "打开设备面板";
        readonly devicePicker: "Android 设备";
        readonly deviceSwitching: "切换中…";
        readonly deviceStreaming: "实时";
        readonly deviceOnline: "在线";
        readonly deviceEmulators: "模拟器";
        readonly devicePhysical: "实体设备";
        readonly deviceAvds: "可用 AVD";
        readonly deviceAvdHint: "用 android_boot 启动";
        readonly deviceNone: "未连接设备";
        readonly followActive: "自动跟随";
        readonly followHint: "面板自动跟随 agent 的最新目标设备";
        readonly followResume: "恢复跟随";
        readonly switchFailed: "切换失败";
        readonly errForbidden: "请求被拒绝（仅限本机可信浏览器）";
        readonly errBadMethod: "该路由不接受此请求方法";
        readonly errBadContentType: "该路由需要 JSON 请求";
        readonly errBadRequest: "请求格式不正确";
        readonly errDeviceUnknown: "设备未连接——运行 android_devices，或用 android_boot 启动模拟器";
        readonly errDeviceOffline: "设备尚未就绪（adb 报告为 offline）";
        readonly errDeviceUnauthorized: "设备未授权这台电脑——请在手机上允许 USB 调试，然后重试";
        readonly errDeviceBusy: "另一台设备正在推流；在设备列表里选择它即可切换";
        readonly errStreamNotRunning: "该设备没有正在运行的画面流";
        readonly errStreamFailed: "设备画面流启动失败";
        readonly errTokenInvalid: "访问链接已过期，刷新即可重新获取";
        readonly errScreenshotMissing: "截图文件已不存在";
        readonly errAdbUnavailable: "此主机没有可用的 adb——请安装 Android platform-tools";
        readonly errUnavailable: "设备不可用";
    };
};
export type AndroidCopy = {
    readonly [Key in keyof typeof COPY.en]: string;
};
export declare function androidCopy(locale: string | undefined): AndroidCopy;
/** Human-readable byte size for the screenshot caption. */
export declare function formatBytes(bytes: number | undefined): string | undefined;
export {};
