const test = require('node:test')
const assert = require('node:assert/strict')
const path = require('node:path')
const { readFile } = require('node:fs/promises')

const root = path.join(__dirname, '..')

test('browser model tools remain user-authorized, background-capable, structured and secret-blind', async () => {
  const [main, html, renderer, preload] = await Promise.all([
    readFile(path.join(root, 'electron', 'main.cjs'), 'utf8'),
    readFile(path.join(root, 'renderer', 'index.html'), 'utf8'),
    readFile(path.join(root, 'renderer', 'browser-sidebar.js'), 'utf8'),
    readFile(path.join(root, 'electron', 'preload.cjs'), 'utf8')
  ])
  assert.match(main, /requireBrowserForModel/u)
  assert.doesNotMatch(main, /function requireBrowserForModel[\s\S]{0,700}tab-not-visible/u)
  assert.match(main, /backgroundThrottling: false/u)
  assert.match(main, /dataPlane: \{ primary: 'cdp-dom', structuredRefs: true, loopbackApi: true, screenshotRequired: false/u)
  assert.match(main, /transport: 'authenticated-loopback-json'/u)
  assert.match(main, /allowBlankNavigation = action === 'navigate' \|\| action === 'tabOpen'/u)
  assert.match(main, /allowBlankNavigation && url === 'about:blank'/u)
  assert.match(main, /browserSecurityPolicy\.modelBootstrapNavigate/u)
  assert.match(main, /trustedPrivateOrigins: browserModelBootstrapTrustedPrivateOrigins\(\)/u)
  assert.match(main, /if \(action === 'observe'\) return observeBrowserForModel\(context\.signal\)/u)
  assert.match(main, /surface: browserSidebarVisible && browserContentVisible \? 'visible' : 'background'/u)
  assert.match(main, /\['click', 'type'\]\.includes\(action\)/u)
  assert.match(main, /redactSensitiveText/u)
  assert.match(main, /browserSecurityPolicy\.modelAction/u)
  assert.match(main, /HARNESS_DESKTOP_BROWSER_STATE_FILE/u)
  assert.match(main, /captureBrowserForModel/u)
  assert.match(main, /browserDomDiagnostics/u)
  assert.match(main, /const accessibleName = element/u)
  assert.match(main, /const implicitRole = element/u)
  assert.match(main, /removeAttribute\(referenceAttribute\)/u)
  assert.match(main, /browserDiagnostics = new BrowserDiagnostics\(\)/u)
  assert.match(main, /createBrowserTab/u)
  assert.match(main, /switchBrowserTab/u)
  assert.match(main, /closeBrowserTab/u)
  assert.match(main, /downloads: browserDownloads/u)
  assert.match(main, /viewport:/u)
  assert.match(main, /browser-action-unsupported/u)
  assert.match(main, /Page\.handleJavaScriptDialog/u)
  assert.match(main, /modelBrowserAction\(input = \{\}, context = \{\}\)/u)
  assert.match(main, /browserOperations\.modelTicket\(signal\)/u)
  assert.match(main, /observeBrowserForModel\(context\.signal\)/u)
  assert.match(main, /browserOperations\.cancelModelActions\(\)/u)
  assert.match(main, /tab\.navigationLane\?\.cancelModel\('model-control-stop'\)/u)
  assert.match(main, /browserSecurityPolicy\?\.pauseModelControl\(\)/u)
  assert.match(main, /browserSecurityPolicy\.resumeModelControl\(\)/u)
  assert.match(main, /browserControlServer\?\.resumeScope\('browser'\)/u)
  assert.match(main, /return modelBrowserAction\(input, context\)/u)
  assert.match(main, /browserSecurityPolicy\?\.isModelStopped/u)
  assert.match(main, /const requestSignal = ticket && typeof ticket === 'object' \? ticket\.signal : null/u)
  assert.match(main, /requestSignal\?\.addEventListener\('abort', cancelFromRequest/u)
  assert.match(main, /Input\.dispatchMouseEvent/u)
  assert.match(main, /Input\.dispatchKeyEvent/u)
  assert.doesNotMatch(main, /function dispatchModelBrowserInput[\s\S]{0,400}contents\.sendInputEvent/u)
  assert.match(main, /await publishBrowserState\(\)/u)
  assert.match(main, /new BrowserSecurityPolicy\(browserPolicyOptions\(\)\)[\s\S]{0,180}pauseModelControl/u)
  assert.doesNotMatch(main, /Runtime\.evaluate|Page\.addScriptToEvaluateOnNewDocument/u)
  assert.match(html, /浏览器控制 · Computer Use/u)
  assert.match(html, /内置浏览器可在后台运行，右栏只是可选预览/u)
  assert.match(html, /结构化 CDP\/DOM 引用/u)
  assert.match(html, /上传、下载与提交继续按事务确认/u)
  assert.doesNotMatch(html, /id="browserGrantCurrent"|id="browserRevokeCurrent"|id="browserResumeModel"/u)
  assert.match(renderer, /允许 AI 控制/u)
  assert.match(renderer, /confirmBrowserModelAction/u)
  assert.match(main, /sharedComputerUseControlState/u)
  assert.match(main, /requireSharedComputerUseForBrowser/u)
  assert.match(main, /computer-use-authorization-required/u)
  assert.match(main, /effectiveActions = control\.active/u)
  assert.match(main, /await setComputerUseEnabled\(false\)/u)
  assert.doesNotMatch(renderer, /grantCurrentBrowserOrigin|revokeCurrentBrowserOrigin|resumeBrowserModelControl/u)
  assert.doesNotMatch(renderer, /executeJavaScript|document\.cookie/u)
  for (const channel of ['browser:confirmModelAction', 'browser:newTab', 'browser:switchTab', 'browser:closeTab', 'computerUse:requestAuthorization', 'computerUse:authorize']) {
    assert.ok(preload.includes(channel))
    assert.ok(main.includes(channel))
  }
})
