const test = require('node:test')
const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..')
const main = readFileSync(path.join(root, 'electron/main.cjs'), 'utf8')
const preload = readFileSync(path.join(root, 'electron/preload.cjs'), 'utf8')
const renderer = readFileSync(path.join(root, 'renderer/app.js'), 'utf8')
const helper = readFileSync(path.join(root, 'scripts/component-update-helper.cjs'), 'utf8')
const bootstrap = readFileSync(path.join(root, 'electron/bootstrap.cjs'), 'utf8')

test('component updates participate in normal checks and require explicit restart action', () => {
  assert.match(main, /component: componentResult/)
  assert.match(main, /ipcMain\.handle\('componentUpdates:apply'/)
  assert.match(preload, /applyComponentUpdates: \(\) => ipcRenderer\.invoke\('componentUpdates:apply'\)/)
  assert.match(renderer, /showComponentUpdateNotice\(result\.component\)/)
  assert.match(renderer, /await api\.stageComponentUpdates\(\)/)
  assert.match(renderer, /await api\.applyComponentUpdates\(\)/)
  assert.match(renderer, /原子切换组件并通过健康检查确认或自动回滚/)
  assert.match(helper, /recovery restart pid=/)
  assert.match(helper, /args\.filter\(value => value !== '--component-health-check'\)/)
  assert.match(bootstrap, /New component shell failed before health confirmation; rolling back/)
  assert.match(bootstrap, /rollbackUnhealthyActivation\(store, error\)/)
  assert.match(bootstrap, /HARNESS_DESKTOP_BUNDLED_ROOT = bundledRoot/)
  assert.match(bootstrap, /layout\.runtimeRoot === bundledRoot \? '' : layout\.runtimeRoot/)
  assert.match(main, /process\.env\.HARNESS_DESKTOP_BUNDLED_ROOT/)
  assert.match(main, /`--user-data-dir=\$\{userDataOverride\}`/)
})
