const test = require('node:test')
const assert = require('node:assert/strict')
const os = require('node:os')
const path = require('node:path')
const { mkdtemp, readFile, rm } = require('node:fs/promises')
const { ensureDesktopComputerUsePlugin } = require('../electron/bridge/desktop-computer-use-plugin-service.cjs')

test('Computer Use is built in with pushed session/permanent unlimited authorization and permanent auto-restore', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'computer-use-'))
  try {
    const repositoryRoot = path.resolve(__dirname, '..')
    const bundledRoot = path.join(repositoryRoot, 'plugins', 'dsh-desktop-computer-use')
    assert.equal((await ensureDesktopComputerUsePlugin({ dshHome: root, bundledRoot })).patchChanged, true)
    assert.equal((await ensureDesktopComputerUsePlugin({ dshHome: root, bundledRoot })).patchChanged, false)

    const [plugin, manifestText, client, main, preload, renderer] = await Promise.all([
      readFile(path.join(bundledRoot, 'lib', 'index.js'), 'utf8'),
      readFile(path.join(bundledRoot, 'package.json'), 'utf8'),
      readFile(path.join(bundledRoot, 'lib', 'client.js'), 'utf8'),
      readFile(path.join(repositoryRoot, 'electron', 'main.cjs'), 'utf8'),
      readFile(path.join(repositoryRoot, 'electron', 'preload.cjs'), 'utf8'),
      readFile(path.join(repositoryRoot, 'renderer', 'app.js'), 'utf8')
    ])
    const manifest = JSON.parse(manifestText)

    assert.match(plugin, /const inject = \['systemPrompt', 'tools'\]/u)
    assert.match(plugin, /Computer Use is a last-resort visual fallback, not the default way to operate software/u)
    assert.match(plugin, /use the narrowest available structured data-plane tool or API/u)
    assert.match(plugin, /Do not call computer_use status, targets, or screenshot merely because an application is visible/u)
    assert.match(plugin, /browser_control is mandatory whenever its structured CDP\/DOM channel is available/u)
    assert.match(plugin, /Computer Use is a built-in desktop skill/u)
    assert.match(plugin, /never ask the user to install it or add a skill card/u)
    assert.match(plugin, /'status', 'requestAuthorization', 'targets', 'select', 'screenshot', 'click', 'type', 'scroll'/u)
    assert.match(plugin, /pushes an authorization card above the dialog/u)
    assert.match(plugin, /unlimited is true/u)
    assert.match(plugin, /same grant and enabled state are shared with background-capable browser_control/u)
    assert.match(plugin, /user authorizes only once/u)
    assert.match(plugin, /browser_control can run its internal browser in the background through structured CDP\/DOM references/u)
    assert.match(plugin, /Harness Desktop target remains capturable and controllable while its main window is hidden or minimized/u)
    assert.match(plugin, /never substitute Computer Use screenshot coordinates/u)
    assert.match(plugin, /browser_control keeps its own credential, payment, and transaction safety boundaries/u)
    assert.match(plugin, /without per-action confirmation/u)
    assert.match(plugin, /UAC\/system\/elevated\/sensitive-window/u)
    assert.match(plugin, /no Shell or scripts are exposed/u)
    assert.match(plugin, /installSettingsSection/u)
    assert.match(plugin, /Settings > Plugins > Plugin configuration/u)
    assert.match(plugin, /cannot grant itself authorization/u)
    assert.match(plugin, /automatically restores the shared control session when the app launches/u)
    assert.doesNotMatch(plugin, /never starts control merely because the app launched/u)
    assert.doesNotMatch(plugin, /仅在用户明确开启后截取或操作 Harness Desktop 自身窗口/u)

    assert.equal(manifest.exports['./client'], './lib/client.js')
    assert.equal(manifest.dsh?.client?.platform, 'web')
    assert.equal(manifest.dsh?.client?.immediately, true)
    assert.ok(manifest.dsh.client.inject.includes('@deepseek-ai/dsh-client-ui-settings-plugins'))
    assert.match(client, /settings\.plugin\.item/u)
    assert.match(client, /computer-use-toggle/u)
    assert.match(client, /computer-use-revoke-permanent/u)
    assert.match(client, /trusted Host authorization card/u)
    assert.match(client, /cannot choose its scope/u)
    assert.match(client, /unlimited mode bypasses application policy, per-action confirmation/u)
    assert.doesNotMatch(client, /authorize-session|authorize-forever/u)
    assert.match(client, /computer-use-refresh/u)
    assert.match(client, /computer-use-status/u)
    assert.match(client, /computer-use-toggle/u)
    assert.match(client, /computer-use-revoke-permanent/u)
    for (const action of ['computer-use-refresh', 'computer-use-status', 'computer-use-toggle', 'computer-use-revoke-permanent']) {
      assert.match(renderer, new RegExp(action, 'u'), `desktop renderer missing ${action} bridge`)
    }
    assert.match(renderer, /__HARNESS_DESKTOP_COMPUTER_USE_STATE__/u)
    assert.match(renderer, /harness-desktop:computer-use-state/u)
    assert.match(renderer, /api\.setComputerUseEnabled\(enabled\)/u)
    assert.match(renderer, /api\.revokeComputerUsePermanentGrant\(\)/u)
    assert.match(renderer, /computerUsePluginMutationPending/u)
    assert.match(renderer, /if \(computerUsePluginMutationPending\) return/u)
    assert.doesNotMatch(renderer, /pluginMutation|setComputerUseAppPolicy/u)

    assert.match(main, /new ComputerUseAppPolicy/u)
    assert.match(main, /new WindowsComputerUse/u)
    assert.match(main, /refreshComputerUseTargets/u)
    assert.match(main, /Number\(window\.pid\) === process\.pid/u)
    assert.match(main, /revalidateComputerUseTarget/u)
    assert.match(main, /requestComputerUseAuthorization/u)
    assert.match(main, /authorizeComputerUse/u)
    assert.match(main, /sharedComputerUseControlState/u)
    assert.match(main, /syncBrowserControlWithComputerUse/u)
    assert.match(main, /requireSharedComputerUseForBrowser/u)
    assert.match(main, /browserSecurityPolicy\.setUnifiedControl\(control\.active\)/u)
    assert.match(main, /computerUseUnlimited \? null : requireComputerConfirmation/u)
    assert.match(main, /grant\.json/u)
    assert.match(main, /mainWindow\.webContents\.capturePage\(undefined, \{ stayHidden: true, stayAwake: true \}\)/u)
    assert.match(main, /if \(image\.isEmpty\(\)\) throw Object\.assign\(new Error\('Harness Desktop 后台画面暂不可用。'\)/u)
    assert.doesNotMatch(main, /function captureHarnessComputerUseScreenshot\(\)[\s\S]{0,500}mainWindow\.isVisible\(\)/u)
    assert.doesNotMatch(main, /target\.kind === 'window'[\s\S]{0,2500}Harness Desktop 主窗口当前不可见/u)
    assert.match(main, /webviewTag: true,\s+backgroundThrottling: false/u)
    assert.match(main, /nativeImage\.createFromBitmap/u)
    assert.match(main, /verifyExternalComputerUseSurface/u)
    assert.match(main, /screenshot-required/u)
    assert.match(main, /target-surface-changed/u)
    assert.match(main, /若任务有结构化工具或 API，请改用结构化通道/u)
    assert.match(main, /sensitive-input-blocked/u)
    assert.match(main, /powerMonitor\.on\('lock-screen'/u)
    assert.match(main, /computerUse:setDefaultAccess/u)
    assert.match(main, /computerUse:setAppOverride/u)
    assert.match(main, /async function authorizeComputerUse[\s\S]{0,900}computerUseUnlimited = true[\s\S]{0,400}setComputerUseEnabled\(true\)/u)
    const restoreGrant = main.slice(main.indexOf('async function restoreComputerUseGrant()'), main.indexOf('function queueComputerUseSystemTransition(action)'))
    assert.match(restoreGrant, /computerUseAuthorizedScope = 'forever'[\s\S]*setComputerUseEnabled\(true\)/u)
    assert.doesNotMatch(restoreGrant, /setComputerUseEnabled\(false\)/u)
    assert.match(main, /pauseComputerUseForSystemInterruption/u)
    assert.match(main, /resumeComputerUseAfterSystemInterruption/u)
    assert.match(main, /powerMonitor\.on\('unlock-screen'[\s\S]{0,350}resumeComputerUseAfterSystemInterruption/u)
    assert.match(main, /powerMonitor\.on\('resume'[\s\S]{0,350}resumeComputerUseAfterSystemInterruption/u)
    assert.match(client, /一键开启窗口读取、点击、输入和滚动/u)
    assert.match(client, /按 Esc 可随时停止/u)
    assert.match(client, /软件启动时自动恢复/u)
    assert.match(client, /Always on \(restored after restart\)/u)
    assert.doesNotMatch(main, /desktopCapturer/u)

    for (const channel of ['computerUse:requestAuthorization', 'computerUse:authorize', 'computerUse:decline', 'computerUse:revokePermanent', 'computerUse:policy', 'computerUse:setDefaultAccess', 'computerUse:setAppOverride', 'computerUse:revokeAppOverride']) {
      assert.ok(main.includes(channel), `main missing ${channel}`)
      assert.ok(preload.includes(channel), `preload missing ${channel}`)
    }
  } finally {
    await rm(root, { recursive: true, force: true })
  }
})
