const test = require('node:test')
const assert = require('node:assert/strict')
const { mkdtemp, readFile, rm, writeFile } = require('node:fs/promises')
const { tmpdir } = require('node:os')
const path = require('node:path')
const { pathToFileURL } = require('node:url')
const YAML = require('yaml')

const root = path.resolve(__dirname, '..')
const service = require('../electron/bridge/desktop-files-plugin-service.cjs')

async function plugin() {
  return import(pathToFileURL(path.join(root, 'plugins/dsh-desktop-files/lib/index.js')).href)
}

test('file upload names are normalized and cannot create paths', async () => {
  const { safeFileName } = await plugin()
  assert.equal(safeFileName('../report.txt'), '_report.txt')
  assert.equal(safeFileName('folder\\draft.md'), 'folder_draft.md')
  assert.equal(safeFileName(' 计划.md '), '计划.md')
  assert.throws(() => safeFileName('..'), /invalid file name/)
})

test('uploads stay in the workspace, preserve collisions and are observable', async t => {
  const directory = await mkdtemp(path.join(tmpdir(), 'dsh-files-'))
  t.after(() => rm(directory, { recursive: true, force: true }))
  const { listUploads, saveUpload } = await plugin()
  const first = await saveUpload(directory, 'report.txt', Buffer.from('one'))
  const second = await saveUpload(directory, 'report.txt', Buffer.from('two'))
  assert.equal(first.path, 'uploads/report.txt')
  assert.equal(second.path, 'uploads/report-1.txt')
  const files = await listUploads(directory)
  assert.deepEqual(new Set(files.map(file => file.path)), new Set(['uploads/report.txt', 'uploads/report-1.txt']))
  assert.equal(files.every(file => file.size === 3), true)
})

test('downloads require a regular workspace-contained relative path', async t => {
  const directory = await mkdtemp(path.join(tmpdir(), 'dsh-download-'))
  const outside = await mkdtemp(path.join(tmpdir(), 'dsh-outside-'))
  t.after(() => Promise.all([rm(directory, { recursive: true, force: true }), rm(outside, { recursive: true, force: true })]))
  await writeFile(path.join(directory, 'inside.txt'), 'ok')
  await writeFile(path.join(outside, 'outside.txt'), 'no')
  const { resolveDownload } = await plugin()
  const inside = await resolveDownload(directory, 'inside.txt')
  assert.equal(inside.info.size, 2)
  await assert.rejects(resolveDownload(directory, '../outside.txt'), error => error.code === 'FILES_PATH_ESCAPE')
  await assert.rejects(resolveDownload(directory, path.join(outside, 'outside.txt')), error => error.code === 'FILES_INVALID_PATH')
})

test('file plugin installation is additive and idempotent', async t => {
  const directory = await mkdtemp(path.join(tmpdir(), 'dsh-file-plugin-'))
  t.after(() => rm(directory, { recursive: true, force: true }))
  const file = path.join(directory, 'cordis.patch.yml')
  assert.equal(await service.ensurePatchEntry(file), true)
  assert.equal(await service.ensurePatchEntry(file), false)
  const entries = YAML.parse(await readFile(file, 'utf8')).flatMap(row => row.insert || [])
  assert.equal(entries.filter(item => item.id === 'desktop-files' && item.name === 'dsh-desktop-files').length, 1)
})

test('file UI uploads by direct user choice and prepares, but never auto-sends, edits', async () => {
  const source = await readFile(path.join(root, 'plugins/dsh-desktop-files/lib/client.js'), 'utf8')
  assert.match(source, /type:\s*["']file["']/)
  assert.match(source, /\/api\/desktop-files\/upload/)
  assert.match(source, /method:\s*["']POST["']/)
  assert.match(source, /inputActions\.setDraft/)
  assert.match(source, /检查后由你手动发送/)
  assert.doesNotMatch(source, /inputActions\.(submit|send)/)
  assert.doesNotMatch(source, /ipcRenderer|desktopHarness/)
  assert.doesNotThrow(() => new Function(source))
})

test('file UI supports accessible multi-file drag and drop without bypassing upload policy', async () => {
  const source = await readFile(path.join(root, 'plugins/dsh-desktop-files/lib/client.js'), 'utf8')
  assert.match(source, /multiple:\s*true/)
  assert.match(source, /function isFileDrag\(event\)/)
  assert.match(source, /onDragEnter:\s*onDragEnter/)
  assert.match(source, /onDragOver:\s*onDragOver/)
  assert.match(source, /onDragLeave:\s*onDragLeave/)
  assert.match(source, /onDrop:\s*onDrop/)
  assert.match(source, /event\.dataTransfer\.files/)
  assert.match(source, /dragDepth\.current/)
  assert.match(source, /event\.key === "Enter" \|\| event\.key === " "/)
  assert.match(source, /file\.size > 50 \* 1024 \* 1024/)
  assert.match(source, /ddf-drop-active/)
  assert.match(source, /var style = document\.querySelector\("style\[data-plugin='dsh-desktop-files'\]"\)/)
  assert.match(source, /if \(!style\.isConnected\) document\.head\.appendChild\(style\)/)
  assert.doesNotMatch(source, /querySelector\("style\[data-plugin='dsh-desktop-files'\]"\)\) return/)
  assert.match(source, /\.ddf-view\{[^}]*height:auto;[^}]*overflow:visible;[^}]*padding:[^}]*72px/)
  assert.doesNotMatch(source, /\.ddf-view\{[^}]*height:100%;[^}]*overflow:auto/)
  assert.match(source, /@media\(max-width:820px\)/)
  assert.match(source, /@media\(prefers-reduced-motion:reduce\)/)
  assert.doesNotMatch(source, /readAsDataURL|webkitGetAsEntry|showOpenFilePicker/)
})

test('file view opens at the top instead of inheriting a previous scroll position', async () => {
  const source = await readFile(path.join(root, 'plugins/dsh-desktop-files/lib/client.js'), 'utf8')
  assert.match(source, /function resetViewScroll\(node\)/)
  assert.match(source, /node\.scrollTop = 0/)
  assert.match(source, /parent\.scrollTop = 0/)
  assert.match(source, /useLayoutEffect\(function \(\)/)
  assert.match(source, /requestAnimationFrame\(function \(\) \{ resetViewScroll\(node\); \}\)/)
  assert.match(source, /new IntersectionObserver/)
  assert.match(source, /visible && !wasVisible/)
  assert.match(source, /ref: viewRef, className: "ddf-view"/)
})
