const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const path = require('node:path')
const test = require('node:test')

test('guest preload preserves native image drops and turns other local files into visible references', () => {
  const source = readFileSync(path.resolve(__dirname, '..', 'electron', 'guest-preload.cjs'), 'utf8')
  assert.match(source, /webUtils\.getPathForFile\(file\)/)
  assert.match(source, /nativeImageTypes/)
  assert.match(source, /dispatchNativeImages\(nativeImages\)/)
  assert.match(source, /ipcRenderer\.invoke\('attachments:inspect'/)
  assert.match(source, /\[data-composer-card\] textarea/)
  assert.match(source, /dispatchEvent\(new InputEvent\('input'/)
  assert.match(source, /event\.stopImmediatePropagation\(\)/)
  assert.match(source, /if \(references\.length === 0\) return/)
})
