const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..')
const runtime = fs.readFileSync(path.join(root, 'mobile/android/app/src/main/assets/mobile-runtime.js'), 'utf8')
const iosRuntime = fs.readFileSync(path.join(root, 'mobile/ios/HarnessMobile/Resources/mobile-runtime.js'), 'utf8')
const androidCss = fs.readFileSync(path.join(root, 'mobile/android/app/src/main/assets/mobile-compat.css'), 'utf8')
const iosCss = fs.readFileSync(path.join(root, 'mobile/ios/HarnessMobile/Resources/mobile-compat.css'), 'utf8')
const client = fs.readFileSync(path.join(root, 'plugins/dsh-agent-teams/lib/client.js'), 'utf8')

test('official Agent Teams exposes stable mobile navigation and context slots', () => {
  assert.match(client, /"data-mobile-slot": "agent-teams\.navigation"/u)
  assert.match(client, /item\.id === "projectTasks" \? "navigation\.tasks" : item\.id === "board" \? "navigation\.agents"/u)
  assert.match(client, /"data-mobile-slot": "agent-teams\.workspace"/u)
  assert.match(client, /"data-mobile-slot": "agent-teams\.context"/u)
  assert.match(client, /"data-harness-mobile-session-id": String\(props\.sessionId \|\| ""\)/u)
  assert.match(client, /"data-harness-mobile-team-id": team \? String\(teamId\(team\)\) : undefined/u)
  assert.match(client, /"data-mobile-slot": "agent-teams\.context-switcher"/u)
  assert.match(client, /"data-harness-mobile-team-id": String\(teamId\(team\)\)/u)
  assert.match(client, /props && props\.session && typeof props\.session\.sessionId === "string"/u)
  assert.match(client, /"harness-mobile-session-context"/u)
  assert.match(client, /name: "conversation\.input\.dock", id: "agent-teams-mobile-session-context"/u)
})

test('team canvas and durable task details expose authoritative entity identifiers', () => {
  assert.match(client, /"data-mobile-slot": "agent-teams\.canvas"/u)
  assert.match(client, /"data-mobile-slot": "agent-teams\.task-detail"/u)
  assert.match(client, /"data-mobile-slot": "agent-teams\.task-detail\.trigger"/u)
  assert.match(client, /"data-harness-mobile-task-id": String\(taskId\(task\)\)/u)
})

test('project tasks expose project and task references without name guessing', () => {
  assert.match(client, /"data-mobile-slot": "tasks\.workspace"/u)
  assert.match(client, /"data-mobile-slot": "tasks\.context"/u)
  assert.match(client, /"data-harness-mobile-project-bound": "true"/u)
  assert.doesNotMatch(client.slice(client.indexOf('function ProjectTasksWorkspace'), client.indexOf('function normalizeProjectFoundationsState')), /projectRef|sessionId|actorRef/u)
  assert.match(client, /"data-mobile-slot": "tasks\.item"/u)
  assert.match(client, /"data-harness-mobile-task-id": String\(safeTask\.taskRef\)/u)
})

test('mobile team source context is explainable and switches through an authoritative session choice', () => {
  assert.match(runtime, /const officialSourceContext = \(\) =>/u)
  assert.match(runtime, /团队属于来源会话，不会因项目名称相同而合并/u)
  assert.match(runtime, /选择其他项目或会话/u)
  assert.match(runtime, /source\?\.scrollIntoView/u)
  assert.doesNotMatch(runtime, /当前项目 · 已绑定/u)
})

test('mobile Scheduled Tasks reuses only the authoritative reminders and project automation workspace', () => {
  assert.match(client, /"aria-labelledby": "dat-automation-title"/u)
  assert.match(client, /"aria-labelledby": "dat-session-schedules"/u)
  assert.match(client, /"aria-labelledby": "dat-project-automation"/u)
  assert.match(client, /fetch\("\/api\/desktop-schedules\/state\?sessionId="/u)
  assert.match(client, /fetch\("\/api\/agent-teams\/project\/automations\/state"/u)
  assert.match(runtime, /const openOfficialScheduledTasks = shell => waitForOfficialWorkspace/u)
  assert.match(runtime, /domain\.id === 'tasks'[^]*dat-automation-title/u)
  assert.doesNotMatch(runtime, /mobileTasksState|renderMobileTasksHub|loadMobileTasksHub|harnessMobileTasksHub/u)
  assert.doesNotMatch(runtime, /\/api\/agent-teams\/project\/tasks\/state/u)
})

test('Android and iOS reuse the official Agent Teams workspace without duplicate task projections', () => {
  assert.equal(runtime, iosRuntime)
  assert.equal(androidCss, iosCss)
  for (const source of [runtime, iosRuntime]) {
    assert.doesNotMatch(source, /mobileTasksState|renderMobileTasksHub|loadMobileTasksHub|harnessMobileTasksHub|taskProjectionState/u)
  }
  const start = client.indexOf('    function taskBoardColumn(task)')
  const end = client.indexOf('    function taskBoardAttempt(task)', start)
  assert.ok(start >= 0 && end > start)
  const boardProjection = client.slice(start, end)
  assert.match(boardProjection, /taskBoardPermissionAttention\(task\)/u)
  assert.match(boardProjection, /status === "unknown" \|\| status === "denied" \|\| status === "unavailable"/u)
  assert.match(boardProjection, /policy === "confirm_each"[^]*outcome === "outcome_unknown"/u)
  assert.doesNotMatch(boardProjection, /progressPercent|\.percent\b|百分比/u)
  assert.match(client, /boardPending: "Ready · 就绪"/u)
  assert.match(client, /boardProgress: "Running · 执行中"/u)
  assert.match(client, /boardBlocked: "Attention · 需关注"/u)
  assert.match(client, /boardCompleted: "Done · 已完成"/u)
})
