const test = require('node:test')
const assert = require('node:assert/strict')
const { mkdtempSync, readFileSync } = require('node:fs')
const os = require('node:os')
const path = require('node:path')

const { ensureMobileControlPlugin } = require('../electron/bridge/mobile-control-plugin-service.cjs')

test('bundled mobile control plugin installs into the DSH web profile idempotently', async () => {
  const home = mkdtempSync(path.join(os.tmpdir(), 'harness-mobile-control-plugin-'))
  const bundledRoot = path.join(__dirname, '..', 'plugins', 'dsh-mobile-control')
  const first = await ensureMobileControlPlugin({ dshHome: home, bundledRoot })
  const second = await ensureMobileControlPlugin({ dshHome: home, bundledRoot })
  assert.equal(first.version, '1.0.37')
  assert.equal(first.patchChanged, true)
  assert.equal(second.patchChanged, false)
  assert.match(readFileSync(path.join(first.destination, 'lib', 'index.js'), 'utf8'), /android_control/)
  const patch = readFileSync(path.join(home, 'profiles', 'web', 'cordis.patch.yml'), 'utf8')
  assert.equal((patch.match(/dsh-mobile-control/g) || []).length, 1)
})
