const test = require('node:test')
const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const path = require('node:path')

const { normalizeState } = require('../electron/store/app-state-store.cjs')

const root = path.join(__dirname, '..')
const read = file => readFileSync(path.join(root, file), 'utf8')

test('native appearance page has a persistent wallpaper library between themes and interface modes', () => {
  const html = read('renderer/index.html')
  const renderer = read('renderer/app.js')
  const guest = read('renderer/theme-integration.js')
  assert.match(html, /id="skinChooseWallpaperEngine"[^>]*>导入当前 Wallpaper Engine 壁纸</)
  assert.match(html, /id="skinBrowseWallpaperEngine"[^>]*>浏览 Wallpaper Engine 壁纸…</)
  assert.match(html, /id="skinThemeTab"[^>]*>主题皮肤<\/button>\s*<button id="skinWallpaperTab"[^>]*>壁纸库<\/button>\s*<button id="skinModeTab"[^>]*>界面模式/u)
  assert.match(html, /id="skinWallpaperPane"/)
  assert.match(html, /id="skinWallpaperLibraryItems"[^>]*role="list"/)
  assert.match(html, /id="skinWallpaperLibraryEmpty"/)
  assert.match(html, /id="skinWallpaperEnginePicker"/)
  assert.match(html, /id="skinWallpaperEngineStatus"/)
  assert.match(html, /id="skinWallpaperEngineItems"/)
  assert.match(html, /id="skinWallpaperEngineSync"[^>]*disabled>同步当前项目源/)
  assert.match(html, /id="skinWallpaperEngineRescan"/)
  assert.match(html, /id="skinWallpaperEngineManual"/)
  // The settings entry on the desktop routes to the in-project native page.
  assert.match(renderer, /\} else if \(target\.hostname === 'open-appearance'\) \{\s*openSkinPicker\(\{ fromSettings: target\.searchParams\.get\('source'\) === 'settings' \}\)/u)
  assert.match(renderer, /api\.listWallpaperEngineProjects\(\)/)
  assert.match(renderer, /api\.importCurrentWallpaperEngine\(\)/)
  assert.match(renderer, /api\.applyWallpaperEngineProject\(directory\)/)
  assert.match(renderer, /api\.applyWallpaper\(id\)/)
  assert.match(renderer, /api\.deleteWallpaper\(id\)/)
  assert.match(renderer, /card\.addEventListener\('dblclick'/)
  assert.match(renderer, /themeIntegration\.createSkinPickerHost\(/)
  assert.match(renderer, /skinPickerHost\.apply\(/)
  assert.match(renderer, /closeSkinPicker\(\)/)
  assert.match(renderer, /api\.syncWallpaperEngine\(\)/)
  assert.match(renderer, /skinWallpaperEngineSync\.disabled = !wallpaperEngineBound/)
  assert.match(renderer, /wallpaperEngineProject/)
  assert.match(guest, /request\('open-appearance', \{ source: 'settings' \}\)/)
  assert.match(guest, /__HARNESS_DESKTOP_CLOSE_SETTINGS_DIALOG__/)
  assert.match(guest, /dialog\.dataset\.hdAppearanceHost = 'true'/)
  // The injected browser panel is kept only for the mobile runtime.
  assert.match(guest, /const mobile = document\.documentElement\.dataset\.harnessMobile === 'true'/)
  assert.match(guest, /if \(!mobile && skinButton\) return/)
  assert.match(guest, /panel = createPanel\(\)/)
  assert.match(guest, /外观与界面模式/)
  assert.match(guest, /restore-appearance/)
})

test('desktop shell exposes bounded wallpaper library IPC and uses managed local copies', () => {
  const preload = read('electron/preload.cjs')
  const main = read('electron/main.cjs')
  const wallpaperService = read('electron/bridge/wallpaper-service.cjs')
  assert.match(preload, /importCurrentWallpaperEngine: \(\) => ipcRenderer\.invoke\('appearance:importCurrentWallpaperEngine'\)/)
  assert.match(preload, /listWallpaperEngineProjects: \(\) => ipcRenderer\.invoke\('appearance:listWallpaperEngineProjects'\)/)
  assert.match(preload, /applyWallpaperEngineProject: value => ipcRenderer\.invoke\('appearance:applyWallpaperEngineProject', value\)/)
  assert.match(preload, /applyWallpaper: value => ipcRenderer\.invoke\('appearance:applyWallpaper', value\)/)
  assert.match(preload, /deleteWallpaper: value => ipcRenderer\.invoke\('appearance:deleteWallpaper', value\)/)
  assert.match(preload, /syncWallpaperEngine: \(\) => ipcRenderer\.invoke\('appearance:syncWallpaperEngine'\)/)
  assert.match(main, /ipcMain\.handle\('appearance:listWallpaperEngineProjects'/)
  assert.match(main, /ipcMain\.handle\('appearance:importCurrentWallpaperEngine'/)
  assert.match(main, /ipcMain\.handle\('appearance:applyWallpaperEngineProject'/)
  assert.match(main, /ipcMain\.handle\('appearance:applyWallpaper'/)
  assert.match(main, /ipcMain\.handle\('appearance:deleteWallpaper'/)
  assert.match(main, /ipcMain\.handle\('appearance:syncWallpaperEngine'/)
  assert.match(main, /require\('\.\/bridge\/wallpaper-library\.cjs'\)/)
  assert.match(main, /function syncBoundWallpaperEngine\(\)/)
  assert.match(main, /async function importCurrentWallpaperEngine\(\)/)
  assert.match(main, /existing\.signature === signature/)
  assert.match(main, /canReuse[\s\S]*applyWallpaperLibraryItem\(existing\.id\)/u)
  assert.match(main, /const wallpaperEngineSync = process\.platform === 'win32'/)
  assert.match(main, /wallpaper-\$\{randomUUID\(\)\.toLowerCase\(\)\}/u)
  assert.match(wallpaperService, /MAX_WALLPAPER_LIBRARY_BYTES = 8 \* 1024 \* 1024 \* 1024/u)
  assert.match(main, /assertManagedWallpaperLibraryCapacity/u)
  assert.match(main, /Startup and ordinary card application always use the managed local copy/u)
  assert.match(main, /async function applyWallpaperLibraryItem\(value\)/)
  assert.match(main, /return readAppearancePayload\(\)/)
  const applyBody = main.slice(main.indexOf('async function applyWallpaperLibraryItem'), main.indexOf('async function deleteWallpaperLibraryItem'))
  assert.doesNotMatch(applyBody, /resolveWallpaperEngine|project\.json|Steam/u)
  assert.match(main, /function scheduleWallpaperAssetRemoval\(fileName, attempt = 0\)/)
  const deleteBody = main.slice(main.indexOf('async function deleteWallpaperLibraryItem'), main.indexOf('async function removeCustomThemeBackground'))
  assert.match(deleteBody, /const payload = await appearancePayload\(\)[\s\S]*scheduleWallpaperAssetRemoval\(item\.cachedFile\)[\s\S]*return payload/u)
  assert.doesNotMatch(main, /wallpaperEngineLibraryScan\(\) *return appearancePayload/u)
})

test('Wallpaper Engine binding is validated and discarded when unsafe', () => {
  const windows = process.platform === 'win32'
  const dir = windows
    ? 'C:\\Steam\\steamapps\\workshop\\content\\431960\\1234'
    : '/Steam/steamapps/workshop/content/431960/1234'
  const bound = normalizeState({ appearance: { customTheme: { wallpaperEngineProject: dir, wallpaperEngineSignature: '1:2:3:4' } } })
  assert.equal(bound.appearance.customTheme.wallpaperEngineProject, dir)
  assert.equal(bound.appearance.customTheme.wallpaperEngineSignature, '1:2:3:4')
  const unsafe = normalizeState({ appearance: { customTheme: { wallpaperEngineProject: '../../escape', wallpaperEngineSignature: 'abc;rm' } } })
  assert.equal(unsafe.appearance.customTheme.wallpaperEngineProject, null)
  assert.equal(unsafe.appearance.customTheme.wallpaperEngineSignature, null)
})
