const test = require('node:test')
const assert = require('node:assert/strict')
const { access, cp, mkdir, mkdtemp, readFile, rm, writeFile } = require('node:fs/promises')
const os = require('node:os')
const path = require('node:path')
const YAML = require('yaml')
const { ensurePluginMarketplace } = require('../electron/bridge/plugin-marketplace-service.cjs')

const bundledRoot = path.resolve(__dirname, '..', 'node_modules', 'dsh-plugin-marketplace')

test('marketplace is installed in the user DSH profile and registered once', async t => {
  const dshHome = await mkdtemp(path.join(os.tmpdir(), 'harness-marketplace-'))
  t.after(() => rm(dshHome, { recursive: true, force: true }))
  const first = await ensurePluginMarketplace({ dshHome, bundledRoot })
  assert.equal(first.action, 'installed')
  assert.equal(first.patchChanged, true)
  assert.equal(first.translationReady, true)
  await access(path.join(first.destination, 'lib', 'index.js'))
  const translatedClient = await readFile(path.join(first.destination, 'lib', 'client.js'), 'utf8')
  assert.match(translatedClient, /HARNESS_DESKTOP_AUTO_ZH_SUMMARY_V1/)
  assert.match(translatedClient, /自动翻译/)
  const second = await ensurePluginMarketplace({ dshHome, bundledRoot })
  assert.equal(second.action, 'preserved')
  assert.equal(second.patchChanged, false)
  assert.equal(second.translationReady, true)
  const patch = YAML.parse(await readFile(path.join(dshHome, 'profiles', 'web', 'cordis.patch.yml'), 'utf8'))
  assert.equal(patch.flatMap(row => row.insert || []).filter(row => row.id === 'plugin-marketplace').length, 1)
})

test('marketplace registration preserves existing patch entries and custom YAML tags', async t => {
  const dshHome = await mkdtemp(path.join(os.tmpdir(), 'harness-marketplace-patch-'))
  t.after(() => rm(dshHome, { recursive: true, force: true }))
  const profile = path.join(dshHome, 'profiles', 'web')
  await mkdir(profile, { recursive: true })
  await writeFile(path.join(profile, 'cordis.patch.yml'), '- insert:\n    - id: existing\n      config: !!js process.platform\n')
  await ensurePluginMarketplace({ dshHome, bundledRoot })
  const text = await readFile(path.join(profile, 'cordis.patch.yml'), 'utf8')
  assert.match(text, /id: existing/)
  assert.match(text, /!!js process\.platform/)
  assert.match(text, /id: plugin-marketplace/)
})

test('a newer user-updated marketplace is never overwritten by a desktop update', async t => {
  const dshHome = await mkdtemp(path.join(os.tmpdir(), 'harness-marketplace-newer-'))
  t.after(() => rm(dshHome, { recursive: true, force: true }))
  const destination = path.join(dshHome, 'profiles', 'web', 'node_modules', 'dsh-plugin-marketplace')
  await mkdir(path.dirname(destination), { recursive: true })
  await cp(bundledRoot, destination, { recursive: true })
  const pkgFile = path.join(destination, 'package.json')
  const pkg = JSON.parse(await readFile(pkgFile, 'utf8'))
  pkg.version = '9.9.9'
  await writeFile(pkgFile, `${JSON.stringify(pkg, null, 2)}\n`)
  await writeFile(path.join(dshHome, 'harness-desktop-marketplace.json'), JSON.stringify({ managed: true }))
  const result = await ensurePluginMarketplace({ dshHome, bundledRoot })
  assert.equal(result.action, 'preserved')
  assert.equal(JSON.parse(await readFile(pkgFile, 'utf8')).version, '9.9.9')
  assert.equal(result.translationReady, false)
})

test('packaged marketplace resolves from the physical app.asar.unpacked directory', async t => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'harness-marketplace-asar-'))
  const dshHome = path.join(root, 'dsh-home')
  const virtualRoot = path.join(root, 'app.asar', 'node_modules', 'dsh-plugin-marketplace')
  const unpackedRoot = path.join(root, 'app.asar.unpacked', 'node_modules', 'dsh-plugin-marketplace')
  t.after(() => rm(root, { recursive: true, force: true }))
  await mkdir(path.dirname(unpackedRoot), { recursive: true })
  await cp(bundledRoot, unpackedRoot, { recursive: true })

  const result = await ensurePluginMarketplace({ dshHome, bundledRoot: virtualRoot })

  assert.equal(result.action, 'installed')
  await access(path.join(result.destination, 'lib', 'client.js'))
})
