const test = require('node:test')
const assert = require('node:assert/strict')
const os = require('node:os')
const path = require('node:path')
const { promisify } = require('node:util')
const { createHash, generateKeyPairSync } = require('node:crypto')
const { execFile, execFileSync } = require('node:child_process')
const { existsSync, realpathSync } = require('node:fs')
const { mkdtemp, mkdir, readdir, rm, writeFile } = require('node:fs/promises')
const { pathToFileURL } = require('node:url')
const execFileAsync = promisify(execFile)
const runtimeUrl = pathToFileURL(path.resolve(__dirname, '..', 'plugins', 'dsh-agent-teams', 'lib', 'project-foundations-runtime.js')).href
const bundledGit = path.resolve(__dirname, '..', 'third_party', 'mingit', 'cmd', 'git.exe')
function gitExecutable() { if (process.platform === 'win32' && existsSync(bundledGit)) return bundledGit; const command = process.platform === 'win32' ? 'where' : 'which'; return realpathSync(execFileSync(command, ['git'], { encoding: 'utf8' }).trim().split(/\r?\n/u)[0]) }
const gitCommand = gitExecutable(), allowedGitRoot = gitCommand === bundledGit ? path.resolve(__dirname, '..', 'third_party', 'mingit') : path.dirname(path.dirname(gitCommand))
async function git(cwd, args) { return String((await execFileAsync(gitCommand, args, { cwd, windowsHide: true, env: { ...process.env, GIT_TERMINAL_PROMPT: '0', GCM_INTERACTIVE: 'Never' } })).stdout).trim() }
async function fixture(options = {}) {
  const { ProjectFoundationsRuntime } = await import(runtimeUrl), root = await mkdtemp(path.join(os.tmpdir(), 'foundations-runtime-')), source = path.join(root, 'source'), foundations = path.join(root, 'foundations'); await mkdir(source); await git(source, ['init']); await writeFile(path.join(source, 'README.md'), 'initial\n'); await git(source, ['add', '-A']); await git(source, ['-c', 'user.name=Runtime Test', '-c', 'user.email=test@localhost', 'commit', '-m', 'initial'])
  const execution = Object.freeze({}), projectRef = `project_${'F'.repeat(26)}`, task = { id: 'task_runtime01', title: 'Runtime task', state: 'in_progress', assigneeSessionId: 'session_runtime01', files: ['README.md'] }, trusted = { projectRef, member: { id: 'member_runtime01', sessionId: 'session_runtime01', state: 'running', kind: 'lead' }, task, team: { id: 'team_runtime01', rootLeadSessionId: 'session_runtime01' }, rootSessionHeader: { cwd: source } }; let disposed = false
  const context = { projectRef }; Object.defineProperties(context, { foundationsRoot: { value: foundations }, workspaceStatePath: { value: path.join(foundations, 'workspace.enc.json') }, authorityRoot: { value: path.join(foundations, 'authority') }, worktreeRoot: { value: path.join(foundations, 'worktrees') }, casObjectRoot: { value: path.join(foundations, 'cas-objects') }, casStagingRoot: { value: path.join(foundations, 'cas-staging') }, qualityStatePath: { value: path.join(foundations, 'quality.enc.json') }, defectStatePath: { value: path.join(foundations, 'defect.enc.json') }, outboxStatePath: { value: path.join(foundations, 'outbox.enc.json') }, execution: { value: execution }, actorResolver: { value: async (candidate, requested) => { if (candidate !== execution || requested !== projectRef) throw new Error('stale context'); return {} } }, keyProvider: { value: (domain, requested) => { if (requested !== projectRef) throw new Error('wrong project'); return Buffer.alloc(32, [...domain].reduce((sum, char) => (sum + char.charCodeAt(0)) & 255, 0)) } }, repositoryRefFor: { value: value => { if (!options.allowOtherSource) assert.equal(value, source); return `repository_${'R'.repeat(26)}` } }, dispose: { value: () => { disposed = true; return true } } }); Object.freeze(context)
  let current = trusted; const runnerKeys = options.runner ? generateKeyPairSync('ed25519') : undefined, hash = value => `sha256:${createHash('sha256').update(value).digest('hex')}`, runner = !runnerKeys ? undefined : { runnerHandle: 'runtime-runner', displayName: 'Runtime runner', trust: 'trusted', capabilities: ['unit'], publicKey: runnerKeys.publicKey, plan: { name: 'Runtime plan', suites: [{ suiteRef: 'unit', tier: 'fast', required: true, minimumTrust: 'trusted', minimumTests: 1 }] }, templates: [{ suiteRef: 'unit', templateDigest: hash('template'), environmentDigest: hash('environment'), version: '1', allowedProfiles: ['merge'], timeoutMs: 60_000, maxAttempts: 2 }] }, runtime = new ProjectFoundationsRuntime({ projectEntry: { localProjectFoundationsContext: async () => context }, desktopGitCapability: Object.freeze(Object.defineProperties({}, { gitCommand: { value: gitCommand }, allowedGitRoot: { value: allowedGitRoot } })), trustedAgentResolver: async candidate => { if (candidate !== execution) throw new Error('foreign execution'); return current }, runner }); return { root, source, execution, trusted, runtime, runnerKeys, hash, setTrusted: value => { current = value }, disposed: () => disposed }
}
async function usingFixture(run) { const state = await fixture(); try { await run(state) } finally { await state.runtime.close().catch(() => undefined); await rm(state.root, { recursive: true, force: true }) } }

test('safe probe is cheap and source dirty initializes honestly but blocks every mutation', async () => {
  const clean = await fixture(); try { await assert.rejects(clean.runtime.workspaceOpen(clean.execution), error => error.code === 'PROJECT_FOUNDATIONS_NOT_READY'); const probed = await clean.runtime.probe(); assert.deepEqual(probed, { version: 1, status: 'ready', attention: [] }); assert.equal(existsSync(path.join(clean.root, 'foundations')), false); assert.equal(JSON.stringify(probed).includes(clean.source), false) } finally { await clean.runtime.close().catch(() => undefined); await rm(clean.root, { recursive: true, force: true }) }
  const invalid = await fixture({ allowOtherSource: true }); try { const nonGit = path.join(invalid.root, 'non-git'); await mkdir(nonGit); invalid.setTrusted({ ...invalid.trusted, rootSessionHeader: { cwd: realpathSync(nonGit) } }); assert.deepEqual(await invalid.runtime.probe(), { version: 1, status: 'source_invalid', code: 'PROJECT_FOUNDATIONS_SOURCE_INVALID', attention: ['source_invalid'] }); assert.equal(existsSync(path.join(invalid.root, 'foundations')), false); await assert.rejects(invalid.runtime.initialize(), error => error.code === 'PROJECT_FOUNDATIONS_SOURCE_INVALID'); assert.ok(invalid.runtime.safeState().attention.includes('source_invalid')); assert.equal(invalid.runtime.safeState().lastErrorCode, 'PROJECT_FOUNDATIONS_SOURCE_INVALID'); assert.equal(existsSync(path.join(invalid.root, 'foundations')), false) } finally { await invalid.runtime.close().catch(() => undefined); await rm(invalid.root, { recursive: true, force: true }) }
  const dirty = await fixture(); try { const dirtyFile = path.join(dirty.source, 'dirty.txt'); await writeFile(dirtyFile, 'dirty\n'); const state = await dirty.runtime.initialize(); assert.equal(state.ready, true); assert.equal(state.sourceStatus, 'source_dirty'); assert.ok(state.attention.includes('source_dirty')); dirty.setTrusted({ projectRef: dirty.trusted.projectRef, kind: 'root', sessionId: 'untrusted-worker', rootSessionHeader: { cwd: 'wrong-root' } }); await assert.rejects(dirty.runtime.workspaceOpen(dirty.execution), error => error.code === 'PROJECT_FOUNDATIONS_FORBIDDEN'); dirty.setTrusted(dirty.trusted); await assert.rejects(dirty.runtime.workspaceOpen(dirty.execution), error => error.code === 'PROJECT_FOUNDATIONS_SOURCE_DIRTY'); await rm(dirtyFile, { force: true }); assert.deepEqual(await dirty.runtime.probe(), { version: 1, status: 'ready', attention: [] }); const opened = await dirty.runtime.workspaceOpen(dirty.execution); assert.match(opened.workspaceRef, /^workspace_/u); await dirty.runtime.workspaceClose(dirty.execution); await writeFile(dirtyFile, 'dirty again\n'); await assert.rejects(dirty.runtime.recover(), error => error.code === 'PROJECT_FOUNDATIONS_SOURCE_DIRTY'); assert.equal(dirty.runtime.safeState().sourceStatus, 'source_dirty') } finally { await dirty.runtime.close().catch(() => undefined); await rm(dirty.root, { recursive: true, force: true }) }
})

test('foundation initialization is Host-rooted, safe by default, and workspace sagas replay exactly', async () => usingFixture(async state => {
  const initialized = await state.runtime.initialize(); assert.equal(initialized.ready, true); assert.deepEqual(initialized.attention, ['connector_disabled', 'runner_unavailable']); const conflictRef = 'mergegroup_safeconflict01'; state.runtime.workspaceAuthority.authority.mergeGroups.set(conflictRef, Object.freeze({ state: 'conflicted' })); assert.equal(state.runtime.safeState().attention.includes('merge_conflict'), true); assert.equal(JSON.stringify(state.runtime.safeState()).includes(conflictRef), false); state.runtime.workspaceAuthority.authority.mergeGroups.delete(conflictRef); const serialized = JSON.stringify(state.runtime); for (const forbidden of [state.root, state.source, `repository_${'R'.repeat(26)}`, 'README.md']) assert.equal(serialized.includes(forbidden), false)
  const opened = await state.runtime.workspaceOpen(state.execution); assert.equal(path.isAbsolute(opened.workspacePath), true); const replay = await state.runtime.workspaceOpen(state.execution); assert.equal(replay.workspaceRef, opened.workspaceRef); assert.equal(replay.fencingToken, opened.fencingToken); assert.equal(state.runtime.safeState().workspaceCount, 1); assert.equal(state.runtime.safeState().claimCount, 1)
  const extra = await state.runtime.resourceClaim(state.execution, { mode: 'read', resources: ['README.md'] }); assert.notEqual(extra.claimRef, opened.claimRef); await assert.rejects(state.runtime.resourceClaim(state.execution, { mode: 'write', resources: ['foreign.txt'] }), error => error.code === 'PROJECT_FOUNDATIONS_FORBIDDEN')
  assert.equal((await state.runtime.workspaceClose(state.execution)).closed, true); assert.equal((await state.runtime.workspaceClose(state.execution)).closed, true)
}))

test('publish and receipt-first merge persist artifacts but never land without a runner', async () => usingFixture(async state => {
  await state.runtime.initialize(); const before = state.runtime.workspaceAuthority.authority.headCommit; await state.runtime.workspaceOpen(state.execution); const worktreeRoot = path.join(state.root, 'foundations', 'worktrees'), [physicalRef] = await readdir(worktreeRoot), workspace = path.join(worktreeRoot, physicalRef); await writeFile(path.join(workspace, 'README.md'), 'runtime change\n'); await git(workspace, ['add', '-A']); await git(workspace, ['-c', 'user.name=Runtime Test', '-c', 'user.email=test@localhost', 'commit', '-m', 'runtime change']); const published = await state.runtime.changeSetPublish(state.execution); assert.match(published.bundleDigest, /^sha256:/u); assert.deepEqual(await state.runtime.changeSetPublish(state.execution), published); assert.equal(state.runtime.safeState().queuedChangeSetCount, 1); assert.equal((await state.runtime.workspaceClose(state.execution)).closed, true); state.setTrusted({ projectRef: state.trusted.projectRef, kind: 'root', sessionId: 'root-session', rootSessionHeader: { cwd: state.source } }); const merged = await state.runtime.mergeNext(state.execution); state.setTrusted(state.trusted); assert.equal(merged.merged, true); assert.equal(merged.campaign.state, 'queued'); assert.equal(state.runtime.safeState().campaignCount, 1); assert.equal(state.runtime.safeState().queuedJobCount, 1); assert.equal(state.runtime.safeState().queuedChangeSetCount, 0); assert.equal(state.runtime.workspaceAuthority.authority.headCommit, before); assert.deepEqual(await state.runtime.qualityAdvance(state.execution), { attention: 'runner_unavailable' }); await state.runtime.recover(); assert.equal(state.runtime.workspaceAuthority.authority.headCommit, before); assert.equal((await state.runtime.workspaceClose(state.execution)).closed, true)
}))

test('registered signed runner is the only path that lands a passing merge', async () => {
  const state = await fixture({ runner: true }); try { await state.runtime.initialize(); const before = state.runtime.workspaceAuthority.authority.headCommit; await state.runtime.workspaceOpen(state.execution); const [physicalRef] = await readdir(path.join(state.root, 'foundations', 'worktrees')), workspace = path.join(state.root, 'foundations', 'worktrees', physicalRef); await writeFile(path.join(workspace, 'README.md'), 'signed pass\n'); await git(workspace, ['add', '-A']); await git(workspace, ['-c', 'user.name=Runtime Test', '-c', 'user.email=test@localhost', 'commit', '-m', 'signed pass']); await state.runtime.changeSetPublish(state.execution); const merged = await state.runtime.mergeNext(state.execution); assert.ok(merged.campaign?.campaignRef); const lease = await state.runtime.qualityAdvance(state.execution), quality = state.runtime.quality.orchestrator.qualityAuthority, prepared = quality.prepareAttestation({ planRef: lease.planRef, suiteRef: lease.suiteRef, runnerRef: state.runtime.runnerRef, binding: lease.binding, result: 'pass', counts: { total: 1, passed: 1, failed: 0, skipped: 0 }, environmentDigest: lease.environmentDigest, evidenceDigest: state.hash('evidence'), startedAt: Date.now(), finishedAt: Date.now() }), { signTestAttestation } = await import(pathToFileURL(path.resolve(__dirname, '..', 'plugins', 'dsh-agent-teams', 'lib', 'quality-evidence.js')).href), attestation = signTestAttestation(prepared, state.runnerKeys.privateKey); await state.runtime.qualitySubmit(state.execution, { jobRef: lease.jobRef, runnerRef: state.runtime.runnerRef, leaseToken: lease.leaseToken, attestation, signature: attestation.signature }); assert.notEqual(state.runtime.workspaceAuthority.authority.headCommit, before); state.runtime.workspaceAuthority.authority.mergeGroups.delete(lease.binding.mergeGroupRef); await assert.rejects(state.runtime.qualityAdvance(state.execution, { campaignRef: merged.campaign.campaignRef }), error => error.code === 'PROJECT_FOUNDATION_CAMPAIGN_BINDING_INVALID') } finally { await state.runtime.close().catch(() => undefined); await rm(state.root, { recursive: true, force: true }) }
})

test('signed failing gate creates a local defect and never lands', async () => {
  const state = await fixture({ runner: true }); try { await state.runtime.initialize(); const before = state.runtime.workspaceAuthority.authority.headCommit; await state.runtime.workspaceOpen(state.execution); const [physicalRef] = await readdir(path.join(state.root, 'foundations', 'worktrees')), workspace = path.join(state.root, 'foundations', 'worktrees', physicalRef); await writeFile(path.join(workspace, 'README.md'), 'signed fail\n'); await git(workspace, ['add', '-A']); await git(workspace, ['-c', 'user.name=Runtime Test', '-c', 'user.email=test@localhost', 'commit', '-m', 'signed fail']); await state.runtime.changeSetPublish(state.execution); await state.runtime.mergeNext(state.execution); const lease = await state.runtime.qualityAdvance(state.execution), quality = state.runtime.quality.orchestrator.qualityAuthority, prepared = quality.prepareAttestation({ planRef: lease.planRef, suiteRef: lease.suiteRef, runnerRef: state.runtime.runnerRef, binding: lease.binding, result: 'fail', counts: { total: 1, passed: 0, failed: 1, skipped: 0 }, environmentDigest: lease.environmentDigest, evidenceDigest: state.hash('failure'), startedAt: Date.now(), finishedAt: Date.now() }), { signTestAttestation } = await import(pathToFileURL(path.resolve(__dirname, '..', 'plugins', 'dsh-agent-teams', 'lib', 'quality-evidence.js')).href), attestation = signTestAttestation(prepared, state.runnerKeys.privateKey); await state.runtime.qualitySubmit(state.execution, { jobRef: lease.jobRef, runnerRef: state.runtime.runnerRef, leaseToken: lease.leaseToken, attestation, signature: attestation.signature }); assert.equal(state.runtime.safeState().defectCount, 1); assert.equal(state.runtime.workspaceAuthority.authority.headCommit, before); assert.ok(state.runtime.safeState().attention.includes('connector_disabled')) } finally { await state.runtime.close().catch(() => undefined); await rm(state.root, { recursive: true, force: true }) }
})

test('restart reopens encrypted foundations and exact workspace/claim receipts without duplication', async () => {
  const state = await fixture(); let reopened; try { await state.runtime.initialize(); const first = await state.runtime.workspaceOpen(state.execution); const context = state.runtime.context, capability = state.runtime.desktopGitCapability; await state.runtime.close(); const { ProjectFoundationsRuntime } = await import(runtimeUrl); reopened = new ProjectFoundationsRuntime({ projectEntry: { localProjectFoundationsContext: async () => context }, desktopGitCapability: capability, trustedAgentResolver: async candidate => { if (candidate !== state.execution) throw new Error('foreign'); return state.trusted } }); await reopened.initialize(); const replay = await reopened.workspaceOpen(state.execution); assert.equal(replay.workspaceRef, first.workspaceRef); assert.equal(replay.fencingToken, first.fencingToken); assert.equal(replay.claimRef, first.claimRef); assert.equal(reopened.safeState().workspaceCount, 1); assert.equal(reopened.safeState().claimCount, 1) } finally { await reopened?.close().catch(() => undefined); await state.runtime.close().catch(() => undefined); await rm(state.root, { recursive: true, force: true }) }
})

test('closed published workspace restarts and merges through its permanent bound ChangeSet', async () => {
  const state = await fixture(); let reopened; try { await state.runtime.initialize(); await state.runtime.workspaceOpen(state.execution); const [physicalRef] = await readdir(path.join(state.root, 'foundations', 'worktrees')), workspace = path.join(state.root, 'foundations', 'worktrees', physicalRef); await writeFile(path.join(workspace, 'README.md'), 'restart artifact\n'); await git(workspace, ['add', '-A']); await git(workspace, ['-c', 'user.name=Runtime Test', '-c', 'user.email=test@localhost', 'commit', '-m', 'restart artifact']); await state.runtime.changeSetPublish(state.execution); assert.equal((await state.runtime.workspaceClose(state.execution)).closed, true); const context = state.runtime.context, capability = state.runtime.desktopGitCapability; await state.runtime.close(); const { ProjectFoundationsRuntime } = await import(runtimeUrl); reopened = new ProjectFoundationsRuntime({ projectEntry: { localProjectFoundationsContext: async () => context }, desktopGitCapability: capability, trustedAgentResolver: async () => state.trusted }); await reopened.initialize(); assert.equal((await reopened.workspaceClose(state.execution)).closed, true); assert.equal((await reopened.mergeNext(state.execution)).merged, true); assert.equal((await reopened.workspaceClose(state.execution)).closed, true) } finally { await reopened?.close().catch(() => undefined); await state.runtime.close().catch(() => undefined); await rm(state.root, { recursive: true, force: true }) }
})

test('close repairs the publish-to-anchor crash window before removing the worktree', async () => usingFixture(async state => {
  await state.runtime.initialize(); await state.runtime.workspaceOpen(state.execution); const [physicalRef] = await readdir(path.join(state.root, 'foundations', 'worktrees')), workspacePath = path.join(state.root, 'foundations', 'worktrees', physicalRef); await writeFile(path.join(workspacePath, 'README.md'), 'anchor crash\n'); await git(workspacePath, ['add', '-A']); await git(workspacePath, ['-c', 'user.name=Runtime Test', '-c', 'user.email=test@localhost', 'commit', '-m', 'anchor crash']); const host = state.runtime.workspaceAuthority.authority.exportHostState(), workspace = host.workspaces.find(item => item.state === 'active'), inspected = await state.runtime.git.inspectChangeSet({ workspaceRef: physicalRef, expectedBaseCommit: workspace.baseCommit }), claimRefs = host.claims.filter(item => item.workspaceRef === workspace.workspaceRef && item.state === 'active').map(item => item.claimRef), changeSet = (await state.runtime.workspaceAuthority.mutate('publishChangeSet', { workspaceRef: workspace.workspaceRef, commit: inspected.commit, parentCommit: inspected.parentCommit, diffDigest: inspected.diffDigest, treeDigest: inspected.treeDigest, files: inspected.files, claimRefs, message: 'anchor crash' })).result; await assert.rejects(state.runtime.git.exportBoundChangeSetBundle({ changeSet, cas: state.runtime.cas }), /immutable ChangeSet ref is unavailable/u); assert.equal((await state.runtime.workspaceClose(state.execution)).closed, true); const bound = await state.runtime.git.exportBoundChangeSetBundle({ changeSet, cas: state.runtime.cas }); assert.match(bound.bundleDigest, /^sha256:/u); state.setTrusted({ projectRef: state.trusted.projectRef, kind: 'root', sessionId: 'root-session', rootSessionHeader: { cwd: state.source } }); assert.equal((await state.runtime.mergeNext(state.execution)).merged, true)
}))

test('runner configuration can be added after reopening an existing no-runner quality store', async () => {
  const state = await fixture(); let reopened; try { await state.runtime.initialize(); await state.runtime.workspaceOpen(state.execution); const [physicalRef] = await readdir(path.join(state.root, 'foundations', 'worktrees')), workspace = path.join(state.root, 'foundations', 'worktrees', physicalRef); await writeFile(path.join(workspace, 'README.md'), 'late runner\n'); await git(workspace, ['add', '-A']); await git(workspace, ['-c', 'user.name=Runtime Test', '-c', 'user.email=test@localhost', 'commit', '-m', 'late runner']); await state.runtime.changeSetPublish(state.execution); await state.runtime.mergeNext(state.execution); const context = state.runtime.context, capability = state.runtime.desktopGitCapability; await state.runtime.close(); const keys = generateKeyPairSync('ed25519'), runner = { runnerHandle: 'late-runner', displayName: 'Late runner', trust: 'trusted', capabilities: ['unit'], publicKey: keys.publicKey, plan: { name: 'Late plan', suites: [{ suiteRef: 'unit', tier: 'fast', required: true, minimumTrust: 'trusted', minimumTests: 1 }] }, templates: [{ suiteRef: 'unit', templateDigest: state.hash('late-template'), environmentDigest: state.hash('late-env'), version: '1', allowedProfiles: ['merge'], timeoutMs: 60_000, maxAttempts: 2 }] }, { ProjectFoundationsRuntime } = await import(runtimeUrl); reopened = new ProjectFoundationsRuntime({ projectEntry: { localProjectFoundationsContext: async () => context }, desktopGitCapability: capability, trustedAgentResolver: async () => state.trusted, runner }); await reopened.initialize(); assert.match(reopened.runnerRef, /^runner_/u); assert.equal(reopened.safeState().attention.includes('runner_unavailable'), false); assert.match((await reopened.qualityAdvance(state.execution)).leaseToken, /^lease_/u) } finally { await reopened?.close().catch(() => undefined); await state.runtime.close().catch(() => undefined); await rm(state.root, { recursive: true, force: true }) }
})

test('root initialization needs no assigned task while worker workspace mutations still do', async () => {
  const state = await fixture(); try { state.setTrusted({ projectRef: state.trusted.projectRef, kind: 'root', sessionId: 'root-only', rootSessionHeader: { cwd: state.source } }); assert.equal((await state.runtime.initialize()).ready, true); assert.deepEqual(await state.runtime.mergeNext(state.execution), { merged: false, attention: 'merge_queue_empty' }); await assert.rejects(state.runtime.workspaceOpen(state.execution), error => error.code === 'PROJECT_FOUNDATIONS_FORBIDDEN') } finally { await state.runtime.close().catch(() => undefined); await rm(state.root, { recursive: true, force: true }) }
})

test('failed initialization cleans partial state and can retry safely with fresh trusted root', async () => {
  const state = await fixture(); try { state.setTrusted({ ...state.trusted, rootSessionHeader: { cwd: path.join(state.source, 'missing') } }); await assert.rejects(state.runtime.initialize(), error => error.code === 'PROJECT_FOUNDATIONS_FORBIDDEN'); assert.equal(state.runtime.safeState().ready, false); state.setTrusted(state.trusted); assert.equal((await state.runtime.initialize()).ready, true) } finally { await state.runtime.close().catch(() => undefined); await rm(state.root, { recursive: true, force: true }) }
})

test('fresh trusted task authorization rejects completed and foreign callers before mutation', async () => usingFixture(async state => {
  await state.runtime.initialize(); state.setTrusted({ ...state.trusted, task: { ...state.trusted.task, state: 'completed' } }); await assert.rejects(state.runtime.workspaceOpen(state.execution), error => error.code === 'PROJECT_FOUNDATIONS_FORBIDDEN'); assert.equal(state.runtime.safeState().workspaceCount, 0); state.setTrusted({ ...state.trusted, task: { ...state.trusted.task, files: ['src/**/*.js'] } }); await assert.rejects(state.runtime.workspaceOpen(state.execution), error => error.code === 'PROJECT_FOUNDATIONS_TASK_SCOPE_UNSUPPORTED'); state.setTrusted(state.trusted); await assert.rejects(state.runtime.workspaceOpen(state.execution, { workspacePath: state.root }), /unsupported fields/u); let touched = false; const accessor = {}; Object.defineProperty(accessor, 'message', { enumerable: true, get() { touched = true; return 'x' } }); await assert.rejects(state.runtime.changeSetPublish(state.execution, accessor), /accessor-backed/u); assert.equal(touched, false); const hidden = {}; Object.defineProperty(hidden, 'message', { value: 'hidden' }); await assert.rejects(state.runtime.changeSetPublish(state.execution, hidden), /hidden/u); const symbol = { [Symbol('message')]: 'x' }; await assert.rejects(state.runtime.changeSetPublish(state.execution, symbol), /symbol/u); await assert.rejects(state.runtime.workspaceOpen({}, {}), error => error.code === 'PROJECT_FOUNDATIONS_FORBIDDEN')
}))

test('close drains accepted work, rejects new work synchronously, and disposes the context once', async () => {
  const state = await fixture(); await state.runtime.initialize(); const accepted = state.runtime.workspaceOpen(state.execution), closed = state.runtime.close(); await assert.rejects(state.runtime.workspaceOpen(state.execution), error => error.code === 'PROJECT_FOUNDATIONS_CLOSED'); await accepted; assert.equal(await state.runtime.close(), await closed); assert.equal(state.disposed(), true); await rm(state.root, { recursive: true, force: true })
})
