const test = require('node:test')
const assert = require('node:assert/strict')
const os = require('node:os')
const path = require('node:path')
const { createHash, randomBytes } = require('node:crypto')
const { mkdtemp, rm } = require('node:fs/promises')
const { pathToFileURL } = require('node:url')
const lib = (...parts) => pathToFileURL(path.resolve(__dirname, '..', 'plugins', 'dsh-agent-teams', 'lib', ...parts)).href
const projectRef = `project_${'B'.repeat(24)}`, at = '2026-08-24T03:00:00.000Z'
const base = (type, messageRef) => ({ version: 1, type, messageRef, sentAt: at })
const task = (index = 1, overrides = {}) => ({ taskRef: `task_${index}`, title: `Task ${index}`, status: 'in_progress', revision: 2, requirementsRevision: 1, createdAt: at, updatedAt: at, hasAssignee: true, blockedByCount: 0, ...overrides })
const ledger = sequence => ({ sequence, type: 'run.queued', occurredAt: at, runRef: `run_${sequence}`, definitionRef: 'definition_1', status: 'queued' })
const command = (commandId = 'wire_command_1', overrides = {}) => ({ ...base('task.command', `request_${commandId}`), commandId, resource: 'task', action: 'claim', taskRef: 'task_1', expectedRevision: 1, payload: {}, ...overrides })
const hello = () => ({ ...base('hello', 'hello_1'), supportedVersions: [1], cursors: { task: 0, automation: 0 } })
const capability = (overrides = {}) => ({ ...base('capability', 'capability_1'), replyTo: 'hello_1', writable: true, taskCommands: ['claim', 'transition'], automationCommands: ['approve', 'reject'], maxPageSize: 100, maxInflight: 8, currentCursors: { task: 0, automation: 0 }, resetToken: 'reset_fixed', ...overrides })
function refs(kind, scope) { return `${kind}_${createHash('sha256').update(JSON.stringify(scope)).digest('hex').slice(0, 24)}` }
function peerResolver({ senderDeviceRef }) { return { deviceRef: senderDeviceRef, collaboratorRef: senderDeviceRef === 'authority_device' ? 'authority_owner' : `collaborator_${senderDeviceRef}`, role: senderDeviceRef === 'authority_device' ? 'owner' : 'maintainer', permissions: ['task', 'review'] } }
function executor({ crashAfterEffect = false } = {}) { const receipts = new Map(); let effects = 0, crash = crashAfterEffect; return { get effects() { return effects }, receipts, async getCommandReceipt(input) { return receipts.get(input.commandId) }, async execute(input) { effects += 1; const result = { completedAt: at, task: task(1) }; receipts.set(input.commandId, result); if (crash) { crash = false; const error = new Error('simulated crash'); error.code = 'PROJECT_BUSINESS_SYNC_TIMEOUT'; throw error } return result } } }
function automationExecutor() { const receipts = new Map(); let effects = 0; return { get effects() { return effects }, async getCommandReceipt(input) { return receipts.get(input.commandId) }, async execute(input) { effects += 1; const result = { completedAt: at, run: { runRef: input.runRef, definitionRef: 'definition_1', revision: 2, status: 'queued', createdAt: at }, approval: { decision: input.action === 'approve' ? 'approved' : 'rejected', decidedAt: at } }; receipts.set(input.commandId, result); return result } } }
function taskProvider(count = 2, gap = false) { const values = Array.from({ length: count }, (_, index) => task(index + 1)); return { async currentCursor() { return count }, async readEvents({ afterCursor, limit }) { if (gap) return { gap: true, events: [] }; const events = values.slice(afterCursor, afterCursor + limit).map((value, index) => ({ cursor: afterCursor + index + 1, type: afterCursor + index ? 'task.transitioned' : 'task.created', occurredAt: at, task: value })); return { events, hasMore: afterCursor + events.length < count } }, async readSnapshot({ offset, limit }) { return { cursor: count, totalItems: count, items: values.slice(offset, offset + limit).map(task => ({ task })) } } } }
function automationProvider() { return { async currentCursor() { return 1 }, async readEvents({ afterCursor }) { return afterCursor ? { events: [], hasMore: false } : { events: [{ cursor: 1, type: 'run.queued', occurredAt: at, ledger: ledger(1), run: { runRef: 'run_1', definitionRef: 'definition_1', revision: 1, status: 'queued', createdAt: at } }], hasMore: false } }, async readSnapshot({ offset, limit }) { const items = [{ ledger: ledger(1) }]; return { cursor: 1, totalItems: 1, items: items.slice(offset, offset + limit) } } } }
async function fixture({ mode = 'authority', taskExec = executor(), automationExec = taskExec, resolver = peerResolver, tasks = taskProvider(), automation = automationProvider(), refMaker = refs, maxQueue } = {}) {
  const [{ ProjectBusinessSyncService }, { ProjectBusinessSyncStore }] = await Promise.all([import(lib('project-business-sync-service.js')), import(lib('project-business-sync-store.js'))]); const root = await mkdtemp(path.join(os.tmpdir(), 'sync-service-')), filePath = path.join(root, `${mode}.enc`), key = randomBytes(32)
  const build = () => { const store = new ProjectBusinessSyncStore({ projectRef, filePath, encryptionKey: key, mode, authorityEpoch: 1 }), service = new ProjectBusinessSyncService({ projectRef, localDeviceRef: mode === 'authority' ? 'authority_device' : 'collaborator_device', authorityEpoch: 1, mode, store, peerResolver: resolver, taskExecutor: taskExec, automationExecutor: automationExec, taskEventProvider: tasks, automationLedgerProvider: automation, refFactory: refMaker, clock: () => at, ...(maxQueue === undefined ? {} : { maxQueue }) }); return { store, service } }
  const active = build(); return { root, filePath, key, ...active, taskExec, build }
}
async function using(options, run) { const state = await fixture(options); try { await run(state) } finally { await state.service.close().catch(() => {}); await rm(state.root, { recursive: true, force: true }) } }
async function inbound(service, message, senderDeviceRef = 'peer_device') { const queued = service.enqueue({ message, opened: { senderDeviceRef, authorityEpoch: 1 } }); const result = await service.process({ limit: 1 }); return { queued, result: result.results[0] } }

test('authorization is fresh and precedes every business receipt lookup', async () => using({ resolver: async () => { throw Object.assign(new Error('revoked'), { code: 'PROJECT_BUSINESS_SYNC_MEMBER_REVOKED' }) } }, async ({ service, store }) => {
  let lookedUp = false; const original = store.getBusinessReceipt.bind(store); store.getBusinessReceipt = async input => { lookedUp = true; return original(input) }
  const { result } = await inbound(service, command()); assert.equal(lookedUp, false); assert.equal(result.ok, false); assert.equal(result.code, 'PROJECT_BUSINESS_SYNC_MEMBER_REVOKED'); assert.equal((await store.load()).state.businessReceipts.length, 0); assert.equal((await store.load()).state.outbox.length, 0)
}))

test('same command replays across transports and restart while drift conflicts', async () => using({}, async ({ service, taskExec, build }) => {
  const first = await inbound(service, command()); const second = await inbound(service, command()); assert.equal(first.result.ok, true, JSON.stringify(first.result)); assert.deepEqual(second.result.result, first.result.result); assert.equal(taskExec.effects, 1)
  const drift = await inbound(service, command('wire_command_1', { expectedRevision: 2 })); assert.equal(drift.result.ok, false); assert.equal(drift.result.code, 'PROJECT_BUSINESS_SYNC_REPLAY_CONFLICT'); assert.equal(taskExec.effects, 1)
  await service.close(); const restarted = build(); try { const replay = await inbound(restarted.service, command()); assert.deepEqual(replay.result.result, first.result.result); assert.equal(taskExec.effects, 1) } finally { await restarted.service.close() }
}))

test('effect-to-sync-receipt crash recovers from the stable bottom receipt identity', async () => using({}, async ({ service, store, taskExec }) => {
  const persist = store.recordBusinessReceiptAndEnqueueOutbox.bind(store); let crash = true; store.recordBusinessReceiptAndEnqueueOutbox = async input => { if (crash) { crash = false; throw Object.assign(new Error('crash after bottom effect'), { code: 'PROJECT_BUSINESS_SYNC_TIMEOUT' }) } return persist(input) }
  const first = await inbound(service, command('crash_command')); assert.equal(first.result.ok, false); assert.equal(first.result.code, 'PROJECT_BUSINESS_SYNC_TIMEOUT'); assert.equal(taskExec.effects, 1); assert.equal((await store.load()).state.businessReceipts.length, 0)
  const replay = await inbound(service, command('crash_command')); assert.equal(replay.result.ok, true); assert.equal(replay.result.result.outcome, 'accepted'); assert.equal(taskExec.effects, 1); assert.equal(taskExec.receipts.size, 1); assert.equal((await store.load()).state.businessReceipts.length, 1)
}))

test('stable bottom rejection maps to a fixed receipt without executing an effect', async () => { let executed = false; const rejected = { async getCommandReceipt() { return { outcome: 'rejected', code: 'SECRET_DATABASE_PATH_ERROR' } }, async execute() { executed = true } }; await using({ taskExec: rejected }, async ({ service }) => { const result = await inbound(service, command('bottom_rejected')); assert.equal(result.result.result.outcome, 'rejected'); assert.equal(result.result.result.code, 'PROJECT_BUSINESS_SYNC_INVALID'); assert.equal(executed, false); assert.equal(Object.hasOwn(result.result.result, 'message'), false) }) })

test('task and Automation permissions map failures to fixed public codes', async () => using({ resolver: ({ senderDeviceRef }) => ({ deviceRef: senderDeviceRef, collaboratorRef: 'collaborator_contributor', role: 'contributor', permissions: ['task'] }) }, async ({ service }) => {
  const allowed = await inbound(service, command('task_allowed')); assert.equal(allowed.result.result.outcome, 'accepted')
  const automation = command('automation_denied', { resource: 'automation', action: 'approve', runRef: 'run_1', taskRef: undefined, payload: {} }); delete automation.taskRef
  const denied = await inbound(service, automation); assert.equal(denied.result.ok, false); assert.equal(denied.result.code, 'PROJECT_BUSINESS_SYNC_FORBIDDEN')
}))

test('real signed role permissions map to least-privilege business capabilities', async () => {
  const { ROLE_PERMISSIONS } = await import(lib('project-collaboration.js'))
  const matrix = [
    ['owner', ['claim', 'transition'], ['approve', 'reject']],
    ['maintainer', ['claim', 'transition'], ['approve', 'reject']],
    ['contributor', ['claim', 'transition'], []],
    ['reviewer', [], []],
    ['observer', [], []],
  ]
  for (const [role, taskCommands, automationCommands] of matrix) await using({ resolver: ({ senderDeviceRef }) => ({ deviceRef: senderDeviceRef, collaboratorRef: `collaborator_${role}`, role, permissions: [...ROLE_PERMISSIONS[role]] }) }, async ({ service }) => {
    const result = await inbound(service, { ...hello(), messageRef: `hello_${role}` }); assert.equal(result.result.ok, true); const granted = result.result.result
    assert.deepEqual(granted.taskCommands, taskCommands); assert.deepEqual(granted.automationCommands, automationCommands); assert.equal(granted.writable, taskCommands.length + automationCommands.length > 0)
  })
  await using({ resolver: ({ senderDeviceRef }) => ({ deviceRef: senderDeviceRef, collaboratorRef: 'collaborator_legacy', role: 'owner', permissions: ['task.write', 'automation.approve'] }) }, async ({ service }) => { const result = await inbound(service, { ...hello(), messageRef: 'hello_legacy_permissions' }); assert.equal(result.result.ok, true); assert.equal(result.result.result.writable, false); assert.deepEqual(result.result.result.taskCommands, []); assert.deepEqual(result.result.result.automationCommands, []) })
})

test('trusted maintainer can approve and reject Automation with safe fixed receipts', async () => { const automationExec = automationExecutor(); await using({ automationExec }, async ({ service }) => {
  for (const action of ['approve', 'reject']) { const wire = command(`automation_${action}`, { resource: 'automation', action, runRef: 'run_1', taskRef: undefined, payload: {} }); delete wire.taskRef; const result = await inbound(service, wire); assert.equal(result.result.result.outcome, 'accepted'); assert.equal(result.result.result.approval.decision, action === 'approve' ? 'approved' : 'rejected'); assert.equal(Object.hasOwn(result.result.result.run, 'error'), false) }
  assert.equal(automationExec.effects, 2)
}) })

test('hello and both normal streams produce durable transport-agnostic outbound messages', async () => using({}, async ({ service }) => {
  const greeting = await inbound(service, hello()); assert.equal(greeting.result.result.type, 'capability')
  await inbound(service, { ...base('event.pull', 'pull_task'), stream: 'task', cursor: 0, limit: 100 })
  await inbound(service, { ...base('event.pull', 'pull_auto'), stream: 'automation', cursor: 0, limit: 100 })
  const outbound = await service.pendingOutbound({ limit: 10 }); assert.deepEqual(outbound.entries.map(entry => entry.message.type), ['event.page', 'event.page']); assert.equal(outbound.entries[0].message.events[0].task.taskRef, 'task_1'); assert.equal(outbound.entries[1].message.events[0].ledger.sequence, 1); assert.equal(outbound.entries[1].message.events[0].run.status, 'queued')
  for (const entry of outbound.entries) { const text = JSON.stringify(entry); for (const forbidden of ['actorRef', '"requirements":', 'fileScope', '"body":', 'packet', '"path":']) assert.equal(text.includes(forbidden), false) }
}))

test('hello and pull control receipts survive restart and reject cross-transport ref drift', async () => using({}, async ({ service, store, build }) => {
  const hello = { ...base('hello', 'durable_hello'), supportedVersions: [1], cursors: { task: 0, automation: 0 } }, first = await inbound(service, hello); assert.equal(first.result.ok, true); const exactCapability = first.result.result; await service.close(); let restarted = build(); const replay = await inbound(restarted.service, structuredClone(hello)); assert.deepEqual(replay.result.result, exactCapability); const drift = structuredClone(hello); drift.cursors.task = 1; assert.equal((await inbound(restarted.service, drift)).result.code, 'PROJECT_BUSINESS_SYNC_REPLAY_CONFLICT')
  const pull = { ...base('event.pull', 'durable_pull'), stream: 'task', cursor: 0, limit: 100 }, pageResult = await inbound(restarted.service, pull), exactPage = pageResult.result.result, pageAck = { ...base('ack', 'durable_page_ack'), replyTo: exactPage.messageRef, kind: 'page', stream: 'task', cursor: exactPage.nextCursor, resetToken: exactCapability.resetToken }; await inbound(restarted.service, pageAck); await restarted.service.close(); restarted = build(); const pageReplay = await inbound(restarted.service, structuredClone(pull)); assert.equal(pageReplay.result.ok, true); assert.equal((await restarted.store.load()).state.outbox.some(entry => entry.messageRef === exactPage.messageRef), false); const pullDrift = { ...pull, limit: 99 }; assert.equal((await inbound(restarted.service, pullDrift)).result.code, 'PROJECT_BUSINESS_SYNC_REPLAY_CONFLICT'); await restarted.service.close()
}))

test('new authority boot rejects old normal pull until hello rotates reset-bound capability', async () => {
  let boot = 'old'; const refMaker = (kind, scope) => refs(kind, kind === 'reset' ? { ...scope, boot } : scope), authority = await fixture({ mode: 'authority', refMaker }); let restarted; try { const hello = { ...base('hello', 'same_boot_hello'), supportedVersions: [1], cursors: { task: 0, automation: 0 } }, oldCapability = (await inbound(authority.service, hello, 'collaborator_device')).result.result, oldPull = { ...base('event.pull', 'old_boot_pull'), stream: 'task', cursor: 0, limit: 100 }; assert.equal((await inbound(authority.service, oldPull, 'collaborator_device')).result.ok, true); await authority.service.close(); boot = 'new'; restarted = authority.build(); const stale = await inbound(restarted.service, oldPull, 'collaborator_device'); assert.equal(stale.result.ok, false); assert.equal(stale.result.code, 'PROJECT_BUSINESS_SYNC_RESET_REQUIRED'); const fresh = await inbound(restarted.service, hello, 'collaborator_device'); assert.equal(fresh.result.ok, true); assert.notEqual(fresh.result.result.resetToken, oldCapability.resetToken); assert.notEqual(fresh.result.result.messageRef, oldCapability.messageRef); const loaded = await restarted.store.load(); assert.equal(loaded.state.outbox.some(entry => entry.message.resetToken === oldCapability.resetToken), false) } finally { await authority.service.close().catch(() => {}); await restarted?.service.close().catch(() => {}); await rm(authority.root, { recursive: true, force: true }) }
})

test('authenticated cross-peer receipt ACK cannot clear another peer routed outbox', async () => using({}, async ({ service, store }) => {
  const receiptResult = await inbound(service, command('peer_routed'), 'peer_A'), receipt = receiptResult.result.result; let state = await store.load(); const entry = state.state.outbox.find(item => item.messageRef === receipt.messageRef); assert.equal(entry.targetDeviceRef, 'peer_A')
  const forged = { ...base('ack', 'forged_peer_ack'), replyTo: receipt.messageRef, kind: 'receipt', ackDigest: entry.digest }, denied = await inbound(service, forged, 'peer_B'); assert.equal(denied.result.ok, false); assert.equal(denied.result.code, 'PROJECT_BUSINESS_SYNC_INVALID'); assert.equal((await store.load()).state.outbox.some(item => item.messageRef === receipt.messageRef), true)
  const accepted = await inbound(service, { ...forged, messageRef: 'valid_peer_ack' }, 'peer_A'); assert.equal(accepted.result.ok, true); state = await store.load(); assert.equal(state.state.outbox.some(item => item.messageRef === receipt.messageRef), false)
}))

test('normal and reset providers are repaged below the 32 KiB wire ceiling', async () => {
  const values = Array.from({ length: 100 }, (_, index) => task(index + 1, { title: 'X'.repeat(500) })), provider = gap => ({ async currentCursor() { return 100 }, async readEvents({ afterCursor, limit }) { if (gap) return { gap: true, events: [] }; const events = values.slice(afterCursor, afterCursor + limit).map((task, index) => ({ cursor: afterCursor + index + 1, type: 'task.transitioned', occurredAt: at, task })); return { events, hasMore: afterCursor + events.length < 100 } }, async readSnapshot({ offset, limit }) { return { cursor: 100, totalItems: 100, items: values.slice(offset, offset + limit).map(task => ({ task })) } } })
  await using({ tasks: provider(false) }, async ({ service }) => { await inbound(service, { ...base('hello', 'fat_normal_hello'), supportedVersions: [1], cursors: { task: 0, automation: 0 } }); const page = (await inbound(service, { ...base('event.pull', 'fat_normal'), stream: 'task', cursor: 0, limit: 100 })).result.result; assert.ok(page.events.length < 100); assert.ok(Buffer.byteLength(JSON.stringify(page)) <= 32 * 1024) })
  await using({ tasks: provider(true) }, async ({ service }) => { await inbound(service, { ...base('hello', 'fat_reset_hello'), supportedVersions: [1], cursors: { task: 0, automation: 0 } }); const page = (await inbound(service, { ...base('event.pull', 'fat_reset'), stream: 'task', cursor: 0, limit: 100 })).result.result; assert.ok(page.snapshot.items.length < 100); assert.ok(Buffer.byteLength(JSON.stringify(page)) <= 32 * 1024) })
})

test('normal hasMore page atomically applies, acknowledges, and queues its exact next pull', async () => {
  const authority = await fixture({ mode: 'authority', tasks: taskProvider(150, false) }), collaborator = await fixture({ mode: 'collaborator' }); let reopened; try {
    const greeting = await collaborator.service.bootstrap({ peerDeviceRef: 'authority_device' }), negotiated = await inbound(authority.service, greeting, 'collaborator_device'); await inbound(collaborator.service, negotiated.result.result, 'authority_device')
    let state = await collaborator.store.load(), pull = state.state.outbox.find(entry => entry.message.type === 'event.pull' && entry.message.stream === 'task').message, first = await inbound(authority.service, pull, 'collaborator_device'); assert.equal(first.result.result.events.length, 100); assert.equal(first.result.result.hasMore, true)
    await inbound(collaborator.service, first.result.result, 'authority_device'); state = await collaborator.store.load(); assert.equal(state.state.peerCursors[0].taskCursor, 100); assert.equal(state.state.safeCache.tasks.length, 100); assert.equal(state.state.outbox.some(entry => entry.messageRef === pull.messageRef), false); pull = state.state.outbox.find(entry => entry.message.type === 'event.pull' && entry.message.stream === 'task').message; assert.equal(pull.cursor, 100); const revision = state.revision, outboxCount = state.state.outbox.length
    await collaborator.service.close(); reopened = collaborator.build(); const duplicate = await inbound(reopened.service, first.result.result, 'authority_device'); assert.equal(duplicate.result.ok, true); state = await reopened.store.load(); assert.equal(state.revision, revision); assert.equal(state.state.outbox.length, outboxCount); assert.equal(state.state.outbox.filter(entry => entry.messageRef === pull.messageRef).length, 1)
    const second = await inbound(authority.service, pull, 'collaborator_device'); assert.equal(second.result.result.events.length, 50); assert.equal(second.result.result.hasMore, false); await inbound(reopened.service, second.result.result, 'authority_device'); state = await reopened.store.load(); assert.equal(state.state.peerCursors[0].taskCursor, 150); assert.equal(state.state.safeCache.tasks.length, 150); assert.equal(state.state.outbox.some(entry => entry.message.type === 'event.pull' && entry.message.stream === 'task'), false)
  } finally { await Promise.all([authority.service.close().catch(() => {}), collaborator.service.close().catch(() => {}), reopened?.service.close().catch(() => {})]); await Promise.all([rm(authority.root, { recursive: true, force: true }), rm(collaborator.root, { recursive: true, force: true })]) }
})

test('gap reset over 100 items survives collaborator reopen and commits only its last page', async () => {
  const authority = await fixture({ mode: 'authority', tasks: taskProvider(150, true) }), collaborator = await fixture({ mode: 'collaborator' }); let reopened; try {
    const bootstrap = await collaborator.service.bootstrap({ peerDeviceRef: 'authority_device' }), negotiated = await inbound(authority.service, bootstrap, 'collaborator_device'); await inbound(collaborator.service, negotiated.result.result, 'authority_device')
    const initialTaskPull = (await collaborator.store.load()).state.outbox.find(entry => entry.message.type === 'event.pull' && entry.message.stream === 'task').message, first = await inbound(authority.service, initialTaskPull, 'collaborator_device'); assert.equal(first.result.result.snapshot.items.length, 100); assert.equal(first.result.result.hasMore, true)
    const appliedFirst = await inbound(collaborator.service, first.result.result, 'authority_device'); assert.equal(appliedFirst.result.ok, true, JSON.stringify(appliedFirst.result)); let state = await collaborator.store.load(); assert.equal(state.state.safeCache.tasks.length, 0); assert.equal(state.state.peerCursors[0].taskCursor, 0); assert.equal(state.state.pendingReset.length, 1)
    const nextPull = state.state.outbox.find(entry => entry.message.type === 'event.pull' && entry.message.stream === 'task' && entry.message.resetToken).message; await collaborator.service.close(); reopened = collaborator.build(); const second = await inbound(authority.service, nextPull, 'collaborator_device'); assert.equal(second.result.result.snapshot.items.length, 50)
    await inbound(reopened.service, second.result.result, 'authority_device'); state = await reopened.store.load(); assert.equal(state.state.pendingReset.length, 0); assert.equal(state.state.safeCache.tasks.length, 150); assert.equal(state.state.peerCursors[0].taskCursor, 150)
  } finally { await Promise.all([authority.service.close().catch(() => {}), collaborator.service.close().catch(() => {}), reopened?.service.close().catch(() => {})]); await Promise.all([rm(authority.root, { recursive: true, force: true }), rm(collaborator.root, { recursive: true, force: true })]) }
})

test('duplicate event.page after collaborator restart reuses exact ACK without reviving pull or growing outbox', async () => {
  const authority = await fixture({ mode: 'authority', tasks: taskProvider(2) }), collaborator = await fixture({ mode: 'collaborator' }); let reopened; try {
    const greeting = await collaborator.service.bootstrap({ peerDeviceRef: 'authority_device' }), negotiated = await inbound(authority.service, greeting, 'collaborator_device'); await inbound(collaborator.service, negotiated.result.result, 'authority_device'); let state = await collaborator.store.load(), pull = state.state.outbox.find(entry => entry.message.type === 'event.pull' && entry.message.stream === 'task').message, pageResult = await inbound(authority.service, pull, 'collaborator_device'), page = pageResult.result.result; await inbound(collaborator.service, page, 'authority_device'); state = await collaborator.store.load(); const count = state.state.outbox.length, ackEntry = state.state.outbox.find(entry => entry.message.type === 'ack' && entry.message.kind === 'page'); assert.equal(state.state.outbox.some(entry => entry.messageRef === pull.messageRef), false); await collaborator.service.completeOutboundDelivery({ targetDeviceRef: 'authority_device', messageRef: ackEntry.messageRef, digest: ackEntry.digest }); const deliveredRevision = (await collaborator.store.load()).revision
    await collaborator.service.close(); reopened = collaborator.build(); const duplicate = await inbound(reopened.service, page, 'authority_device'); assert.equal(duplicate.result.ok, true); const after = await reopened.store.load(); assert.equal(after.revision, deliveredRevision + 1); assert.equal(after.state.outbox.length, count); assert.equal(after.state.outbox.some(entry => entry.messageRef === pull.messageRef), false); assert.equal(after.state.safeCache.tasks.length, 2)
  } finally { await Promise.all([authority.service.close().catch(() => {}), collaborator.service.close().catch(() => {}), reopened?.service.close().catch(() => {})]); await Promise.all([rm(authority.root, { recursive: true, force: true }), rm(collaborator.root, { recursive: true, force: true })]) }
})

test('collaborator bootstrap persists authenticated safe capability across restart', async () => using({ mode: 'collaborator' }, async ({ service, store, build }) => {
  const greeting = await service.bootstrap({ peerDeviceRef: 'authority_device' }); let state = await store.load(); assert.equal(state.state.outbox.length, 1); assert.equal(state.state.outbox[0].targetDeviceRef, 'authority_device'); assert.equal(state.state.outbox[0].message.type, 'hello')
  const negotiated = capability({ replyTo: greeting.messageRef }); const first = await inbound(service, negotiated, 'authority_device'); assert.equal(first.result.ok, true); state = await store.load(); assert.equal(state.state.outbox.some(entry => entry.message.type === 'hello'), false); assert.deepEqual(state.state.outbox.map(entry => entry.message.stream).sort(), ['automation', 'task']); assert.ok(state.state.outbox.every(entry => entry.targetDeviceRef === 'authority_device'))
  const persisted = state.state.peerCursors[0].capability; assert.deepEqual({ writable: persisted.writable, taskCommands: persisted.taskCommands, automationCommands: persisted.automationCommands, maxPageSize: persisted.maxPageSize, maxInflight: persisted.maxInflight, currentCursors: persisted.currentCursors }, { writable: negotiated.writable, taskCommands: negotiated.taskCommands, automationCommands: negotiated.automationCommands, maxPageSize: negotiated.maxPageSize, maxInflight: negotiated.maxInflight, currentCursors: negotiated.currentCursors }); assert.equal(persisted.messageRef, negotiated.messageRef); assert.match(persisted.digest, /^[a-f0-9]{64}$/u); const safeCapability = (await store.getCollaboratorCapability()).capability; assert.deepEqual(safeCapability, { writable: negotiated.writable, taskCommands: negotiated.taskCommands, automationCommands: negotiated.automationCommands, maxPageSize: negotiated.maxPageSize, maxInflight: negotiated.maxInflight, currentCursors: negotiated.currentCursors, resetToken: negotiated.resetToken }); assert.equal(JSON.stringify(safeCapability).includes('authority_device'), false); assert.equal(JSON.stringify(safeCapability).includes(negotiated.messageRef), false); const count = state.state.outbox.length; const replay = await inbound(service, negotiated, 'authority_device'); assert.equal(replay.result.ok, true); assert.equal((await store.load()).state.outbox.length, count); await service.close(); const restarted = build(); try { assert.deepEqual((await restarted.store.load()).state.peerCursors[0].capability, persisted); assert.deepEqual((await restarted.store.getCollaboratorCapability()).capability, safeCapability) } finally { await restarted.service.close() }
}))

test('revoked forged capability cannot change persisted peer capability', async () => using({ mode: 'collaborator', resolver: async () => { throw Object.assign(new Error('revoked'), { code: 'PROJECT_BUSINESS_SYNC_MEMBER_REVOKED' }) } }, async ({ service, store }) => {
  const greeting = await service.bootstrap({ peerDeviceRef: 'authority_device' }), before = await store.load(), result = await inbound(service, capability({ messageRef: 'forged_capability', replyTo: greeting.messageRef }), 'authority_device'); assert.equal(result.result.ok, false); assert.equal(result.result.code, 'PROJECT_BUSINESS_SYNC_MEMBER_REVOKED'); const after = await store.load(); assert.equal(after.revision, before.revision); assert.equal(after.state.peerCursors.length, 0); assert.deepEqual(after.state.outbox, before.state.outbox)
}))

test('authority restart reset token prunes old stream controls and restarts collaborator pulls from zero', async () => using({ mode: 'collaborator' }, async ({ service, store }) => {
  const firstHello = await service.bootstrap({ peerDeviceRef: 'authority_device' }); await inbound(service, capability({ replyTo: firstHello.messageRef, resetToken: 'reset_old' }), 'authority_device'); let state = await store.load(), oldPull = state.state.outbox.find(entry => entry.message.type === 'event.pull' && entry.message.stream === 'task').message, oldPage = { ...base('event.page', 'old_page'), replyTo: oldPull.messageRef, stream: 'task', afterCursor: 0, nextCursor: 1, hasMore: false, events: [{ cursor: 1, type: 'task.created', occurredAt: at, task: task(1) }] }; await inbound(service, oldPage, 'authority_device'); state = await store.load(); assert.equal(state.state.peerCursors[0].taskCursor, 1); assert.equal(state.state.safeCache.tasks.length, 1)
  const secondHello = await service.bootstrap({ peerDeviceRef: 'authority_device' }), changed = capability({ messageRef: 'capability_restart', replyTo: secondHello.messageRef, resetToken: 'reset_new', currentCursors: { task: 5, automation: 6 } }); await inbound(service, changed, 'authority_device'); state = await store.load(); assert.equal(state.state.peerCursors[0].taskCursor, 0); assert.equal(state.state.peerCursors[0].automationCursor, 0); assert.equal(state.state.safeCache.tasks.length, 0); const pulls = state.state.outbox.filter(entry => entry.message.type === 'event.pull'); assert.deepEqual(pulls.map(entry => entry.message.cursor), [0, 0]); assert.ok(pulls.every(entry => entry.targetDeviceRef === 'authority_device'))
  const stale = await inbound(service, oldPage, 'authority_device'); assert.equal(stale.result.ok, false); state = await store.load(); assert.equal(state.state.safeCache.tasks.length, 0); assert.equal(state.state.peerCursors[0].taskCursor, 0)
}))

test('collaborator persists a receipt, completes exact command outbox, then durably acks', async () => using({ mode: 'collaborator' }, async ({ service, store }) => {
  const greeting = await service.bootstrap({ peerDeviceRef: 'authority_device' }); await inbound(service, capability({ replyTo: greeting.messageRef }), 'authority_device'); const wire = command('outbound_command'), { businessRequestDigest } = await import(lib('project-business-sync-domain.js')), requestDigest = businessRequestDigest(wire, { senderDeviceRef: 'collaborator_device', authorityEpoch: 1 }); let loaded = await store.load(); await store.enqueueOutbox({ targetDeviceRef: 'authority_device', message: wire, digest: requestDigest, expectedRevision: loaded.revision, queuedAt: at }); loaded = await store.load(); assert.deepEqual(await store.getOutboundCommand({ targetDeviceRef: 'authority_device', commandId: wire.commandId }), { revision: loaded.revision, status: 'pending', message: wire, digest: requestDigest }); const forgedCompletion = { ...base('ack', 'forged_command_ack'), replyTo: wire.messageRef, kind: 'receipt', ackDigest: loaded.state.outbox.find(entry => entry.messageRef === wire.messageRef).digest }, rejectedAck = await inbound(service, forgedCompletion, 'authority_device'); assert.equal(rejectedAck.result.ok, false); assert.equal(rejectedAck.result.code, 'PROJECT_BUSINESS_SYNC_INVALID'); assert.equal((await store.load()).state.outbox.some(entry => entry.messageRef === wire.messageRef), true)
  const receipt = { ...base('task.receipt', 'remote_receipt'), replyTo: wire.messageRef, commandId: wire.commandId, requestDigest, outcome: 'accepted', completedAt: at, task: task(1) }; await inbound(service, receipt, 'authority_device'); loaded = await store.load(); assert.equal(loaded.state.outbox.some(entry => entry.messageRef === wire.messageRef), false); const ack = loaded.state.outbox.find(entry => entry.message.type === 'ack' && entry.message.kind === 'receipt'); assert.equal(ack.message.replyTo, receipt.messageRef); assert.equal(loaded.state.businessReceipts.length, 1); const completedCommand = await store.getOutboundCommand({ targetDeviceRef: 'authority_device', commandId: wire.commandId }); assert.equal(completedCommand.status, 'completed'); assert.deepEqual(completedCommand.message, wire); assert.equal(completedCommand.digest, requestDigest); assert.deepEqual(completedCommand.result, receipt); await service.completeOutboundDelivery({ targetDeviceRef: 'authority_device', messageRef: ack.messageRef, digest: ack.digest }); assert.equal((await store.load()).state.outbox.some(entry => entry.messageRef === ack.messageRef), false); await inbound(service, receipt, 'authority_device'); assert.deepEqual((await store.load()).state.outbox.find(entry => entry.messageRef === ack.messageRef).message, ack.message)
  const bad = { ...receipt, messageRef: 'remote_receipt_bad', requestDigest: 'f'.repeat(64) }; const result = await inbound(service, bad, 'authority_device'); assert.equal(result.result.ok, false); assert.equal(result.result.code, 'PROJECT_BUSINESS_SYNC_REPLAY_CONFLICT')
}))

test('recover never resurrects already-acked historical receipt outbox', async () => using({}, async ({ service, store, taskExec }) => {
  const wire = command('recover_command'), { businessRequestDigest, normalizeBusinessSyncMessage } = await import(lib('project-business-sync-domain.js')), requestDigest = businessRequestDigest(wire, { senderDeviceRef: 'peer_device', authorityEpoch: 1 }), receipt = normalizeBusinessSyncMessage({ ...base('task.receipt', refs('receipt', { senderDeviceRef: 'peer_device', commandId: wire.commandId })), replyTo: wire.messageRef, commandId: wire.commandId, requestDigest, outcome: 'accepted', completedAt: at, task: task(1) })
  await store.recordBusinessReceipt({ senderDeviceRef: 'peer_device', commandId: wire.commandId, requestDigest, receipt, expectedRevision: 0 }); const recovered = await service.recover(); assert.equal(recovered.recovered, 0); assert.equal(recovered.outbound.length, 0); assert.equal(taskExec.effects, 0); assert.equal((await service.recover()).recovered, 0)
}))

test('wire identity, transport, path, hash, and raw error fields are rejected before queueing', async () => using({}, async ({ service }) => {
  const attempts = [
    { message: { ...command('bad_actor'), actorRef: 'attacker' }, opened: { senderDeviceRef: 'peer_device', authorityEpoch: 1 } },
    { message: { ...command('bad_hash'), requestDigest: 'a'.repeat(64) }, opened: { senderDeviceRef: 'peer_device', authorityEpoch: 1 } },
    { message: { ...command('bad_path'), payload: { path: 'C:/secret' } }, opened: { senderDeviceRef: 'peer_device', authorityEpoch: 1 } },
    { message: command('bad_transport'), opened: { senderDeviceRef: 'peer_device', authorityEpoch: 1, transport: 'lan' } },
  ]
  for (const input of attempts) assert.throws(() => service.enqueue(input), error => error.code === 'PROJECT_BUSINESS_SYNC_INVALID')
  assert.equal(service.toJSON().queueDepth, 0); assert.equal(JSON.stringify(service).includes('error'), false)
}))

test('accessors are never invoked and resolver receives and returns only exact trusted peer data', async () => {
  let invoked = 0, resolverInput
  await using({ resolver: input => { resolverInput = input; return { deviceRef: input.senderDeviceRef, collaboratorRef: 'collaborator_peer', role: 'maintainer', permissions: ['task'], extra: true } } }, async ({ service }) => {
    const opened = {}; Object.defineProperty(opened, 'senderDeviceRef', { enumerable: true, get() { invoked += 1; return 'peer_device' } }); Object.defineProperty(opened, 'authorityEpoch', { enumerable: true, value: 1 })
    assert.throws(() => service.enqueue({ message: command('opened_accessor'), opened }), error => error.code === 'PROJECT_BUSINESS_SYNC_INVALID'); assert.equal(invoked, 0)
    const malicious = command('message_accessor'); Object.defineProperty(malicious.payload, 'hidden', { enumerable: true, get() { invoked += 1; return 'secret' } }); assert.throws(() => service.enqueue({ message: malicious, opened: { senderDeviceRef: 'peer_device', authorityEpoch: 1 } }), error => error.code === 'PROJECT_BUSINESS_SYNC_INVALID'); assert.equal(invoked, 0)
    const result = await inbound(service, command('resolver_exact')); assert.equal(result.result.ok, false); assert.equal(result.result.code, 'PROJECT_BUSINESS_SYNC_INVALID'); assert.deepEqual(Object.keys(resolverInput).sort(), ['authorityEpoch', 'senderDeviceRef']); assert.equal(Object.isFrozen(resolverInput), true)
  })
})

test('close drains an already accepted async bootstrap before closing its Store', async () => using({ mode: 'collaborator' }, async ({ service, store }) => {
  const originalLoad = store.load.bind(store); let release, enteredResolve, first = true; const entered = new Promise(resolve => { enteredResolve = resolve }), gate = new Promise(resolve => { release = resolve })
  store.load = async () => { if (first) { first = false; enteredResolve(); await gate } return originalLoad() }
  const accepted = service.bootstrap({ peerDeviceRef: 'authority_device' }); await entered; const closeA = service.close(), closeB = service.close(); assert.equal(closeA, closeB); release(); const greeting = await accepted; assert.equal(greeting.type, 'hello'); await closeA; await assert.rejects(service.recover(), error => error.code === 'PROJECT_BUSINESS_SYNC_CLOSED')
}))

test('bounded queue, per-sender FIFO, close drain, and synchronous rejection are enforced', async () => using({ maxQueue: 2 }, async ({ service }) => {
  service.enqueue({ message: hello(), opened: { senderDeviceRef: 'peer_device', authorityEpoch: 1 } }); service.enqueue({ message: { ...hello(), messageRef: 'hello_2' }, opened: { senderDeviceRef: 'peer_device', authorityEpoch: 1 } }); assert.throws(() => service.enqueue({ message: { ...hello(), messageRef: 'hello_3' }, opened: { senderDeviceRef: 'peer_device', authorityEpoch: 1 } }), error => error.code === 'PROJECT_BUSINESS_SYNC_BACKPRESSURE')
  const closeA = service.close(), closeB = service.close(); assert.equal(closeA, closeB); await closeA; await assert.rejects(service.pendingOutbound(), error => error.code === 'PROJECT_BUSINESS_SYNC_CLOSED'); assert.throws(() => service.enqueue({ message: hello(), opened: { senderDeviceRef: 'peer_device', authorityEpoch: 1 } }), error => error.code === 'PROJECT_BUSINESS_SYNC_CLOSED')
}))
