const assert = require('node:assert/strict')
const { readFile } = require('node:fs/promises')
const path = require('node:path')
const test = require('node:test')

const root = path.resolve(__dirname, '..')

async function source(relative) {
  return readFile(path.join(root, relative), 'utf8')
}

test('all third-party GitHub Actions are pinned to immutable commits', async () => {
  for (const file of ['release.yml', 'publish-production-components.yml', 'verify-component-signing-secret.yml', 'android-mobile-release.yml', 'apple-virtual-tests.yml', 'ci.yml', 'upstream-watch.yml']) {
    const workflow = await source(path.join('.github', 'workflows', file))
    const uses = [...workflow.matchAll(/uses:\s+([^\s#]+)@([^\s#]+)/g)]
    assert.ok(uses.length > 0, `${file} must use at least one pinned action`)
    for (const match of uses) assert.match(match[2], /^[0-9a-f]{40}$/, `${file}: ${match[0]}`)
  }
})

test('signed Android publication is exact-dispatch-only and waits for the verified desktop release', async () => {
  const workflow = await source(path.join('.github', 'workflows', 'android-mobile-release.yml'))
  assert.match(workflow, /workflow_dispatch:[\s\S]*tag:[\s\S]*request_id:/u)
  assert.doesNotMatch(workflow, /\n\s+push:|github\.ref_name|github\.run_id|inputs\.tag \|\|/u)
  assert.ok(workflow.includes('RELEASE_TAG: ${{ inputs.tag }}'))
  assert.match(workflow, /run-name: Android \$\{\{ inputs\.tag \}\} · \$\{\{ inputs\.request_id \}\}/u)
  for (const input of ['tag', 'request_id']) {
    assert.match(workflow, new RegExp(`${input}:[\\s\\S]*?required: true`, 'u'))
  }
  assert.ok((workflow.match(/verify-formal-windows-release-identity\.mjs/gu) || []).length >= 3)
  assert.match(workflow, /Waiting for verified desktop release/u)
  assert.match(workflow, /gh release upload "\$RELEASE_TAG"/u)
  assert.match(workflow, /seq 1 180/u)
  assert.match(workflow, /android-universal\.apk\.sha256/u)
  assert.match(workflow, /Preserving the existing immutable APK/u)
  assert.match(workflow, /Verify public signed APK bytes and identity/u)
  assert.doesNotMatch(workflow, /--clobber|assembleDebug|app-debug\.apk/u)
  const desktopWorkflow = await source(path.join('.github', 'workflows', 'release.yml'))
  const recoveryWorkflow = await source(path.join('.github', 'workflows', 'recover-release-from-actions.yml'))
  assert.match(desktopWorkflow, /workflow_dispatch:[\s\S]*source_revision:[\s\S]*request_id:/u)
  assert.match(desktopWorkflow, /run-name: Candidate \$\{\{ inputs\.tag \}\} @ \$\{\{ inputs\.source_revision \}\} · \$\{\{ inputs\.request_id \}\}/u)
  assert.doesNotMatch(desktopWorkflow, /push:[\s\S]*tags:|release-retry\/v|contents: write|stage-draft:|verify-windows-draft:|^  publish:/mu)
  assert.match(desktopWorkflow, /^  prepare-windows-candidate:\r?\n(?:    #[^\r\n]*\r?\n)*    if: \$\{\{ false \}\}$/mu)
  assert.match(desktopWorkflow, /^  verify-windows-candidate:\r?\n    if: \$\{\{ false \}\}$/mu)
  for (const contract of ['Run packaged Windows self-test', 'Verify packaged Windows component health and rollback', 'Current-version portable self-test', 'Current-version installed self-test', 'Current-version Windows uninstaller']) assert.match(desktopWorkflow, new RegExp(contract, 'u'))
  assert.match(desktopWorkflow, /--allow-downgrade --force/u)
  assert.match(desktopWorkflow, /git ls-remote --exit-code --tags origin "refs\/tags\/\$RELEASE_TAG"/u)
  assert.doesNotMatch(desktopWorkflow, /uploads\.github\.com|gh release upload|draft-snapshot\.json|--method PATCH/u)
  assert.match(recoveryWorkflow, /source_run_id:[\s\S]*source_request_id:/u)
  assert.match(recoveryWorkflow, /run-id: \$\{\{ inputs\.source_run_id \}\}/u)
  assert.match(recoveryWorkflow, /^  verify-windows-draft:\r?\n(?:    #[^\r\n]*\r?\n)*    if: \$\{\{ false \}\}$/mu)
  assert.match(recoveryWorkflow, /^  publish:\r?\n    name: Publish unchanged recovered draft\r?\n    needs: recover$/mu)
  assert.match(recoveryWorkflow, /--method PATCH "repos\/\$GITHUB_REPOSITORY\/releases\/\$RELEASE_ID"/u)
  assert.doesNotMatch(recoveryWorkflow, /--clobber|overwrite_files: true|npm run dist/u)
  assert.match(workflow, /--json isDraft/u)
})

test('v1.0.58 one-off installed homepage gate consumes only the current pre-Tag Windows artifact', async () => {
  const workflow = await source(path.join('.github', 'workflows', 'release.yml'))
  const jobStart = workflow.indexOf('  oneoff-v1-0-58-windows-ui-validation:')
  const jobEnd = workflow.indexOf('\n  ios-simulators:', jobStart)
  assert.ok(jobStart > workflow.indexOf('name: desktop-${{ matrix.os }}'))
  assert.ok(jobEnd > jobStart)
  const job = workflow.slice(jobStart, jobEnd)
  const cleanupMarker = workflow.slice(Math.max(0, jobStart - 240), jobStart)
  assert.match(cleanupMarker, /ONE-OFF v1\.0\.58 ONLY:[\s\S]*delete this entire job plus its script and contract[\s\S]*after v1\.0\.58 publication completes/iu)
  assert.match(job, /^    if: \$\{\{ inputs\.tag == 'v1\.0\.58' \}\}$/mu)
  assert.match(job, /^    needs: build$/mu)
  assert.match(job, /ref: \$\{\{ inputs\.source_revision \}\}/u)
  assert.match(job, /GITHUB_SHA\.ToLowerInvariant\(\) -ne \$env:ONEOFF_SOURCE_REVISION/u)
  assert.match(job, /github\.workflow_ref[\s\S]*github\.run_id/u)
  assert.match(job, /actions\/download-artifact@[0-9a-f]{40}[\s\S]*name: desktop-windows-latest[\s\S]*runner\.temp.*github\.run_id/u)
  assert.doesNotMatch(job, /^\s+run-id:/mu)
  assert.match(job, /release-oneoff-v1\.0\.58-windows-ui-validation\.cjs/u)
  assert.match(job, /Install, open the ordinary app, prove its homepage, stop, and uninstall/u)
  assert.doesNotMatch(job, /--self-test|gh release|uploads\.github\.com|contents: write|stable-components|release:publish/u)
  const existingSmoke = workflow.slice(workflow.indexOf('- name: Run Windows installer smoke test'), jobStart)
  assert.match(existingSmoke, /Current-version installed self-test[\s\S]*Current-version Windows uninstaller/u)
})

test('macOS release artifacts are explicitly unsigned with a one-click installer helper', async () => {
  const pkg = JSON.parse(await source('package.json'))
  const builder = await source('scripts/build-release.mjs')
  const workflow = await source(path.join('.github', 'workflows', 'release.yml'))
  assert.equal(pkg.scripts['dist:mac'], 'node scripts/build-release.mjs')
  assert.equal(pkg.build.mac.identity, null)
  assert.notEqual(pkg.build.mac.hardenedRuntime, true)
  assert.notEqual(pkg.build.mac.notarize, true)
  assert.equal(pkg.build.afterAllArtifactBuild, 'scripts/afterAllArtifactBuild.cjs')
  for (const contract of ['CSC_LINK', 'CSC_KEY_PASSWORD', 'APPLE_API_KEY', 'APPLE_API_KEY_ID', 'APPLE_API_ISSUER', 'APPLE_TEAM_ID', "CSC_IDENTITY_AUTO_DISCOVERY === 'true'", 'macOS unsigned packaging refuses Developer ID / notarization environment']) assert.ok(builder.includes(contract), contract)
  assert.match(workflow, /Build unsigned macOS packages/u)
  assert.match(workflow, /CSC_IDENTITY_AUTO_DISCOVERY: 'false'/u)
  assert.match(workflow, /Verify unsigned macOS packages/u)
  for (const forbidden of ['macos-signing', 'xcrun notarytool submit', 'xcrun stapler', 'codesign --verify', 'spctl --assess', 'secrets.APPLE_NOTARY', 'secrets.MACOS_DEVELOPER_ID']) assert.ok(!workflow.includes(forbidden), forbidden)
  const matrixPrefix = workflow.slice(0, workflow.indexOf('steps:'))
  assert.doesNotMatch(matrixPrefix, /MACOS_DEVELOPER_ID|APPLE_NOTARY/u)
})

test('production component preparation binds the private key to target-correct fallbacks', async () => {
  const builder = await source('scripts/prepare-production-components.mjs')
  assert.match(builder, /does not match the public key embedded/u)
  assert.match(builder, /win32-x64[\s\S]*win-x64\.exe/u)
  assert.match(builder, /darwin-x64[\s\S]*mac-x64\.dmg/u)
  assert.match(builder, /darwin-arm64[\s\S]*mac-arm64\.dmg/u)
  assert.match(builder, /validateAndVerifyManifest/u)
  assert.doesNotMatch(builder, /console\.log\([^\n]*(privateKey|privatePem|recoveryKey)/u)
  const publisher = await source(path.join('.github', 'workflows', 'publish-production-components.yml'))
  assert.match(publisher, /HARNESS_COMPONENT_SIGNING_PRIVATE_KEY_BASE64/u)
  assert.match(publisher, /prepare-production-components\.mjs/u)
  assert.match(publisher, /base64 --decode/u)
  assert.match(publisher, /Preserve matching assets and identify missing component assets/u)
  assert.match(publisher, /verify-production-component-staging\.mjs/u)
  assert.match(publisher, /Re-download and verify public component assets/u)
  assert.match(publisher, /run-name: Components \$\{\{ inputs\.tag \}\} · \$\{\{ inputs\.request_id \}\}/u)
  assert.doesNotMatch(publisher, /inputs\.tag \|\||inputs\.request_id \|\|/u)
  for (const input of ['tag', 'product_revision', 'request_id', 'formal_windows_product_revision', 'formal_windows_release_id', 'formal_windows_asset_id', 'formal_windows_asset_name', 'formal_windows_asset_size', 'formal_windows_asset_digest', 'formal_windows_asset_url']) {
    assert.match(publisher, new RegExp(`^      ${input}:\\r?\\n(?:        [^\\r\\n]+\\r?\\n)*?        required: true$`, 'mu'))
  }
  assert.ok((publisher.match(/verify-formal-windows-release-identity\.mjs/gu) || []).length >= 4)
  assert.ok(publisher.lastIndexOf('verify-formal-windows-release-identity.mjs') > publisher.indexOf('git push origin "HEAD:refs/heads/$branch"'))
  assert.doesNotMatch(publisher, /--clobber/u)
  const backup = await source('scripts/configure-component-signing-backup.ps1')
  assert.match(backup, /gh repo create \$BackupRepo --private/u)
  assert.match(backup, /HARNESS_COMPONENT_SIGNING_PRIVATE_KEY_BASE64/u)
  assert.match(backup, /\[Array\]::Clear/u)
  assert.doesNotMatch(backup, /Copy-Item -LiteralPath \$private/u)
  const secretVerifier = await source(path.join('.github', 'workflows', 'verify-component-signing-secret.yml'))
  assert.match(secretVerifier, /verify-component-signing-key\.mjs/u)
  assert.match(secretVerifier, /trap 'rm -f/u)
  assert.doesNotMatch(secretVerifier, /echo "\$COMPONENT_SIGNING_PRIVATE_KEY_BASE64"/u)
})

test('desktop release signing reuses the reviewed component Ed25519 trust root without exposing private material', async () => {
  const componentSources = JSON.parse(await source('component-update-sources.json'))
  const desktopSources = JSON.parse(await source('release-update-sources.json'))
  assert.deepEqual(desktopSources.trustedKeys, componentSources.trustedKeys)
  const contract = await source('electron/bridge/desktop-release-contract.cjs')
  const refresher = await source('scripts/refresh-release-manifest.mjs')
  assert.match(contract, /canonicalJson/u)
  assert.match(contract, /verifySignedObject/u)
  const main = await source('electron/main.cjs')
  const trustLoader = main.match(/async function desktopReleaseTrustedKeys\(\) \{[\s\S]*?\n\}/u)?.[0] || ''
  assert.match(trustLoader, /__HARNESS_COMPONENT_UPDATE__\?\.bundledRoot/u)
  assert.match(trustLoader, /release-update-sources\.json/u)
  assert.doesNotMatch(trustLoader, /process\.env|HARNESS_DESKTOP_UPDATE_FEED/u)
  assert.match(main, /HARNESS_DESKTOP_UPDATE_FEEDS|resolveUpdateFeeds/u)
  assert.doesNotMatch(refresher, /console\.log\([^\n]*(privateKey|privatePem|SIGNING_KEY_FILE)/u)
})

test('release orchestration is resumable and defaults to non-publishing verification', async () => {
  const orchestrator = await source('scripts/release-orchestrator.mjs')
  assert.match(orchestrator, /const through = argument\('through', 'verify'\)/u)
  assert.match(orchestrator, /\.release-state/u)
  assert.match(orchestrator, /process\.env\.npm_execpath/u)
  assert.match(orchestrator, /Skipping completed phase/u)
  assert.match(orchestrator, /cleanSourceRevision/u)
  assert.match(orchestrator, /sourceRevision !== sourceRevision/u)
  assert.match(orchestrator, /Release orchestration requires a clean source tree/u)
  assert.match(orchestrator, /PHASES\.slice\(phaseIndex\)/u)
  assert.match(orchestrator, /readAndroidMobileVersion\(root\)/u)
  assert.match(orchestrator, /android\.integrationVersion !== version \|\| android\.versionName !== version/u)
  assert.doesNotMatch(orchestrator, /versionCode = \$\{mobileCode\}/u)
  assert.match(orchestrator, /test:component-local/u)
  const componentTest = await source('scripts/local-component-update-test.mjs')
  assert.match(componentTest, /path\.join\(root, 'plugins'\)/u)
  assert.match(componentTest, /value\.phase === 'rollback-required'/u)
  assert.match(componentTest, /clearTimeout\(timer\)/u)
  assert.doesNotMatch(orchestrator, /gh release (create|upload)|git push/u)
})
