const assert = require('node:assert/strict')
const { readFile } = require('node:fs/promises')
const path = require('node:path')
const test = require('node:test')

const root = path.resolve(__dirname, '..')

test('desktop candidate proves the signed previous-stable upgrade before Tag creation', async () => {
  const workflow = await readFile(path.join(root, '.github', 'workflows', 'release.yml'), 'utf8')

  assert.match(workflow, /workflow_dispatch:[\s\S]*source_revision:[\s\S]*request_id:/u)
  assert.ok(workflow.includes('group: release-candidate-${{ inputs.tag }}'))
  assert.doesNotMatch(workflow, /release-retry\/v|stage-draft:|verify-windows-draft:|^  publish:|contents: write/mu)
  assert.doesNotMatch(workflow, /gh api --method POST "repos\/\$GITHUB_REPOSITORY\/releases"|uploads\.github\.com|draft-snapshot\.json|--method PATCH/u)
  assert.match(workflow, /prepare-windows-candidate:[\s\S]*verify-windows-candidate:/u)
  assert.match(workflow, /verify-windows-candidate:[\s\S]*needs: prepare-windows-candidate/u)
  assert.match(workflow, /Verify Windows candidate upgrade and installation/u)
  assert.match(workflow, /Bind the signed previous stable Windows installer to an exact public asset/u)
  assert.match(workflow, /validateAndVerifyDesktopReleaseManifest/u)
  assert.match(workflow, /validateAndVerifyManifest/u)
  assert.match(workflow, /component-feeds\/stable\/win32-x64\.json/u)
  assert.match(workflow, /previous-stable-windows-binding/u)
  assert.match(workflow, /candidate-state\/previous-stable\.json/u)
  assert.match(workflow, /Current-run Windows artifact contains an unexpected file set/u)
  assert.match(workflow, /Previous stable installer SHA-256 mismatch/u)
  assert.match(workflow, /Find-DllHoldingProcess[\s\S]*d3dcompiler_47\.dll/u)
  assert.match(workflow, /Previous stable installed self-test JSON failed or reported the wrong version/u)
  assert.match(workflow, /stable-upgrade-profile\.marker/u)
  assert.match(workflow, /\/NORESTARTAPPLICATIONS/u)
  assert.match(workflow, /\/LOGCLOSEAPPLICATIONS/u)
  assert.doesNotMatch(workflow, /\/FORCECLOSEAPPLICATIONS/u)
  assert.match(workflow, /RestartApplications=no contract failed/u)
  assert.match(workflow, /Upgraded installed self-test JSON failed or reported the wrong version/u)
  assert.match(workflow, /Harness-Desktop-\$version-portable-x64\.exe/u)
  assert.match(workflow, /Harness-Desktop-\$version-win-x64\.exe/u)
  assert.match(workflow, /Filter 'unins\*\.exe'/u)
  assert.match(workflow, /Uninstaller left the temporary installation directory behind/u)
})

test('release recovery binds the exact successful candidate run and resumes an exact draft subset', async () => {
  const workflow = await readFile(path.join(root, '.github', 'workflows', 'recover-release-from-actions.yml'), 'utf8')

  assert.match(workflow, /workflow_dispatch:[\s\S]*source_run_id:[\s\S]*source_request_id:[\s\S]*release_id:/u)
  assert.match(workflow, /permissions:\s*\n\s*actions: read\s*\n\s*contents: write/u)
  assert.match(workflow, /run-id: \$\{\{ inputs\.source_run_id \}\}/u)
  for (const job of ['Build windows-latest', 'Build macos-latest', 'Build ubuntu-latest', 'Validate iPhone and iPad simulators', 'Verify Windows candidate upgrade and installation']) {
    assert.match(workflow, new RegExp(job.replaceAll(' ', '\\s'), 'u'))
  }
  assert.match(workflow, /\.head_sha == \$sha[\s\S]*\.head_branch == "main"/u)
  assert.match(workflow, /\.display_title == "Candidate \\\(\$tag\) @ \\\(\$sha\) · \\\(\$request\)"/u)
  assert.match(workflow, /Exact same-run desktop artifact set is unavailable/u)
  assert.match(workflow, /workflow_run\.id == \$run/u)
  assert.match(workflow, /Unexpected private draft assets/u)
  assert.match(workflow, /Duplicate release asset name/u)
  assert.match(workflow, /Preserving verified existing asset/u)
  assert.match(workflow, /gh release upload "\$RELEASE_TAG" "\$file"/u)
  assert.match(workflow, /releases\/assets\/\$id/u)
  assert.match(workflow, /sha256sum -c SHA256SUMS\.txt/u)
  assert.match(workflow, /diff -u <\(jq -S \. draft-snapshot\.json\) <\(jq -S \. current-draft\.json\)/u)
  assert.match(workflow, /--method PATCH "repos\/\$GITHUB_REPOSITORY\/releases\/\$RELEASE_ID"[\s\S]*-F draft=false/u)
  assert.doesNotMatch(workflow, /--clobber|overwrite_files: true|softprops\/action-gh-release|npm run dist/u)
})
