const assert = require('node:assert/strict')
const { readFile } = require('node:fs/promises')
const path = require('node:path')
const test = require('node:test')

const root = path.resolve(__dirname, '..')

test('desktop publication is gated by authenticated draft installation', async () => {
  const workflow = await readFile(path.join(root, '.github', 'workflows', 'release.yml'), 'utf8')

  assert.match(workflow, /stage-draft:[\s\S]*verify-windows-draft:[\s\S]*publish:/u)
  assert.match(workflow, /needs: stage-draft[\s\S]*needs: verify-windows-draft/u)
  const pkg = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'))
  assert.ok(workflow.includes(`group: release-\${{ inputs.tag || (github.ref == 'refs/heads/release-retry/v${pkg.version}' && 'v${pkg.version}') || github.ref_name }}`))
  assert.match(workflow, /Refuse an existing release mutation with atomic REST create/u)
  assert.match(workflow, /gh api --method POST "repos\/\$GITHUB_REPOSITORY\/releases"/u)
  assert.match(workflow, /HTTP 422/u)
  assert.match(workflow, /gh release upload "\$RELEASE_TAG" release-files\/\*/u)
  assert.match(workflow, /Verify exact draft assets and immutable snapshot metadata/u)
  assert.match(workflow, /draft-snapshot\.json/u)
  const projection = '{id,tag_name,target_commitish,draft,name,body,prerelease,assets:([.assets[] | {id,name,size,digest}] | sort_by(.name))}'
  assert.equal(workflow.split(projection).length - 1, 3)
  assert.match(workflow, /verify-windows-draft:[\s\S]*permissions:\s*\n\s*contents: write/u)
  assert.match(workflow, /Authenticated draft download, checksum, install, self-test, and uninstall/u)
  assert.match(workflow, /releases\/assets\/\$\(\$asset\.id\)/u)
  assert.match(workflow, /Authorization = "Bearer \$env:GH_TOKEN"/u)
  assert.match(workflow, /Invoke-WebRequest[\s\S]*-OutFile \$destination/u)
  assert.match(workflow, /\$downloaded\.Length -ne \[int64\]\$asset\.size/u)
  assert.match(workflow, /Snapshot digest mismatch/u)
  assert.match(workflow, /foreach \(\$line in Get-Content -LiteralPath \$checksumPath\)/u)
  assert.match(workflow, /Get-FileHash[\s\S]*SHA256/u)
  assert.match(workflow, /Downloaded files do not exactly match SHA256SUMS\.txt/u)
  assert.match(workflow, /Downloaded files do not exactly match the staged draft snapshot/u)
  assert.match(workflow, /Harness-Desktop-\$version-portable-x64\.exe/u)
  assert.match(workflow, /Start-Process -FilePath \$portable[\s\S]*--self-test/u)
  assert.match(workflow, /--self-test-output=\$portableReport/u)
  assert.match(workflow, /--user-data-dir=\$portableProfile/u)
  assert.match(workflow, /\$portableSelfTest\.ExitCode -ne 0/u)
  assert.match(workflow, /\$portableResult\.ok[\s\S]*\$portableResult\.product\.version -ne \$version/u)
  assert.match(workflow, /Remove-Item[^\n]*\$portableProfile, \$portableReport/u)
  assert.match(workflow, /Harness-Desktop-\$version-win-x64\.exe/u)
  assert.match(workflow, /\/VERYSILENT/u)
  assert.match(workflow, /resources\/app\.asar/u)
  assert.match(workflow, /--self-test-output=\$reportPath/u)
  assert.match(workflow, /\$report\.product\.version -ne \$version/u)
  assert.match(workflow, /Filter 'unins\*\.exe'/u)
  assert.match(workflow, /Uninstaller left the temporary installation directory behind/u)
  assert.match(workflow, /finally \{[\s\S]*Remove-Item/u)
  assert.match(workflow, /Reconfirm draft and assets are unchanged before publication/u)
  assert.match(workflow, /diff -u <\(jq -S \. draft-state\/draft-snapshot\.json\)/u)
  assert.match(workflow, /--draft=false/u)
  assert.doesNotMatch(workflow, /gh release download|uses: softprops\/action-gh-release|--clobber|overwrite_files: true/u)
})

test('release recovery binds successful tag artifacts and resumes an exact draft subset', async () => {
  const workflow = await readFile(path.join(root, '.github', 'workflows', 'recover-release-from-actions.yml'), 'utf8')

  assert.match(workflow, /workflow_dispatch:[\s\S]*source_run_id:[\s\S]*release_id:/u)
  assert.match(workflow, /permissions:\s*\n\s*actions: read\s*\n\s*contents: write/u)
  assert.match(workflow, /run-id: \$\{\{ inputs\.source_run_id \}\}/u)
  for (const job of ['Build windows-latest', 'Build macos-latest', 'Build ubuntu-latest', 'Validate iPhone and iPad simulators']) {
    assert.match(workflow, new RegExp(job.replaceAll(' ', '\\s'), 'u'))
  }
  assert.match(workflow, /\.head_sha == \$sha/u)
  assert.match(workflow, /Unexpected private draft assets/u)
  assert.match(workflow, /Preserving verified existing asset/u)
  assert.match(workflow, /gh release upload "\$RELEASE_TAG" "\$file"/u)
  assert.match(workflow, /releases\/assets\/\$id/u)
  assert.match(workflow, /sha256sum -c SHA256SUMS\.txt/u)
  assert.match(workflow, /diff -u <\(jq -S \. draft-snapshot\.json\) <\(jq -S \. current-draft\.json\)/u)
  assert.match(workflow, /--method PATCH[\s\S]*-F draft=false/u)
  assert.doesNotMatch(workflow, /--clobber|overwrite_files: true|softprops\/action-gh-release/u)
})
