const test = require('node:test')
const assert = require('node:assert/strict')
const path = require('node:path')
const { readFile } = require('node:fs/promises')

const root = path.resolve(__dirname, '..')

test('desktop themes lock the outer viewport while preserving mobile page scrolling', async () => {
  const source = await readFile(path.join(root, 'renderer', 'theme-integration.js'), 'utf8')
  assert.match(source, /:not\(\[data-harness-mobile="true"\]\) body,\s*html\[data-hd-theme\].*:not\(\[data-harness-mobile="true"\]\) #root \{ width:100%; height:100%; min-height:0 !important; overflow:hidden !important; \}/u)
  assert.match(source, /\[data-harness-mobile="true"\] body,\s*html\[data-hd-theme\].*\[data-harness-mobile="true"\] #root \{ min-height:100vh; \}/u)
  assert.match(source, /if \(root\.dataset\.harnessMobile === 'true' \|\| root\.dataset\.hdTheme === 'official'\) return/u)
  assert.match(source, /if \(window\.scrollX !== 0 \|\| window\.scrollY !== 0\) window\.scrollTo\(0, 0\)/u)
  assert.match(source, /applyUiMode\(false\)\s*if \(refreshTheme\) applyTheme\(\)\s*else syncWallpaperVideo\(activeWallpaperTheme\(window\.__HARNESS_DESKTOP_THEME_STATE__ \|\| \{\}\)\)\s*stabilizeWorkbenchViewport\(\)/u)
  assert.match(source, /wallpaperFrameRate = 24/u)
  assert.match(source, /wallpaperMaxPixels = 1920 \* 1080/u)
  assert.match(source, /wallpaperVideoCanvas = document\.createElement\('canvas'\)/u)
  assert.match(source, /const decoder = document\.createElement\('video'\)/u)
  assert.doesNotMatch(source, /document\.body\.(?:prepend|append)\((?:wallpaperVideoDecoder|decoder)\)/u)
  assert.match(source, /const sourceChanged = wallpaperVideoDecoder\?\.dataset\.hdWallpaperSource !== source/u)
  assert.match(source, /releaseWallpaperVideo\(\)\s*const decoder = document\.createElement\('video'\)[\s\S]*?decoder\.dataset\.hdWallpaperSource = source\s*decoder\.src = source\s*decoder\.load\(\)\s*wallpaperVideoDecoder = decoder/u)
  assert.match(source, /video\.pause\(\)\s*video\.removeAttribute\('src'\)\s*delete video\.dataset\.hdWallpaperSource\s*video\.load\(\)/u)
  assert.match(source, /wallpaperVideoCanvas\.width = 0\s*wallpaperVideoCanvas\.height = 0\s*wallpaperVideoCanvas\.remove\(\)/u)
  assert.match(source, /const workbenchReady = Boolean\(workbenchRoot\?\.childElementCount \|\| workbenchRoot\?\.textContent\?\.trim\(\)\)/u)
  assert.match(source, /const shouldPause = wallpaperLifecycleParked \|\| root\.dataset\.hdLowPerformance === 'true' \|\| root\.dataset\.hdReducedMotion === 'true' \|\| document\.hidden \|\| !workbenchReady/u)
  assert.match(source, /if \(shouldPause\) \{\s*releaseWallpaperVideo\(\)\s*releaseWallpaperCanvas\(\)\s*overlay\?\.remove\(\)/u)
  assert.match(source, /const frameInterval = 1000 \/ wallpaperFrameRate[\s\S]*?const elapsed = now - wallpaperLastFrameAt[\s\S]*?wallpaperLastFrameAt = now - \(elapsed % frameInterval\)/u)
  assert.doesNotMatch(source, /wallpaperLastFrameAt = now\s*drawWallpaperFrame/u)
  assert.match(source, /wallpaperVideoFrameRequest = video\.requestVideoFrameCallback[\s\S]*?drawWallpaperFrameWhenDue\(now, video, canvas\)/u)
  assert.match(source, /wallpaperAnimationFrameRequest = window\.requestAnimationFrame\(drawFromAnimationFrame\)/u)
  assert.match(source, /video\.cancelVideoFrameCallback\(wallpaperVideoFrameRequest\)[\s\S]*?window\.cancelAnimationFrame\(wallpaperAnimationFrameRequest\)/u)
  assert.match(source, /Math\.sqrt\(wallpaperMaxPixels \/ \(rawWidth \* rawHeight\)\)/u)
  assert.match(source, /Math\.max\(canvas\.width \/ video\.videoWidth, canvas\.height \/ video\.videoHeight\)/u)
  assert.match(source, /const activeWallpaperTheme = state => state\?\.themeId === 'custom' \? customThemeFromState\(state\) : null/u)
  assert.match(source, /window\.harnessDesktopGuest\?\.onWallpaperLifecycle\?\.\(action => \{[\s\S]*?action === 'park'[\s\S]*?wallpaperLifecycleParked = true\s*releaseWallpaperVideo\(\)\s*releaseWallpaperCanvas\(\)[\s\S]*?action !== 'resume'/u)
  assert.match(source, /if \(action !== 'resume'\) return\s*releaseWallpaperVideo\(\)\s*releaseWallpaperCanvas\(\)\s*document\.querySelector\('\.hd-wallpaper-video-overlay'\)\?\.remove\(\)\s*wallpaperLifecycleParked = false\s*syncWallpaperVideo\(activeWallpaperTheme\(window\.__HARNESS_DESKTOP_THEME_STATE__ \|\| \{\}\)\)/u)
  assert.match(source, /visibilitychange'[\s\S]*?syncWallpaperVideo\(activeWallpaperTheme\(window\.__HARNESS_DESKTOP_THEME_STATE__ \|\| \{\}\)\)/u)
  assert.match(source, /if \(!mobile && syncVideo\) syncWallpaperVideo\(activeWallpaperTheme\(state\)\)/u)
  assert.match(source, /data-hd-wallpaper-kind="video"[\s\S]*?backdrop-filter:none!important/u)
  assert.match(source, /data-hd-wallpaper-kind="video"[\s\S]*?var\(--hd-theme-readable-surface\)/u)
  assert.doesNotMatch(source, /syncWallpaperVideo\(customThemeFromState\(state\)\)/u)
  assert.doesNotMatch(source, /(?:watchdog|location\.reload|\.reload\(\))/iu)
  assert.match(source, /\[data-conversation-scroll\] > \[data-composer-seat\] \{ position:sticky!important; z-index:18; bottom:0!important;[\s\S]*?max-height:min\(58dvh,520px\); overflow-anchor:none; \}/u)
  assert.match(source, /\[data-composer-seat\] \[data-composer-card="true"\] \{ min-height:0!important; max-height:min\(54dvh,480px\); overflow:hidden; \}/u)
  assert.match(source, /\[data-composer-seat\] \[data-input-scroll="true"\] \{ min-height:0!important; max-height:min\(var\(--dsh-composer-text-max-height,280px\),40dvh\)!important; overflow-y:auto;/u)
})

test('custom skins keep composer and question controls readable', async () => {
  const source = await readFile(path.join(root, 'renderer', 'theme-integration.js'), 'utf8')
  const genericComposer = 'html[data-hd-theme]:not([data-hd-theme="official"]) [data-composer-card="true"]'
  const customComposer = 'html[data-hd-theme="custom"][data-hd-skin-tone] [data-composer-card="true"]'

  assert.ok(source.indexOf(genericComposer) >= 0)
  assert.ok(source.indexOf(customComposer) > source.indexOf(genericComposer), 'the equally specific custom surface must follow the generic surface')
  assert.match(source, /html\[data-hd-theme="custom"\]\[data-hd-skin-tone\] \[data-composer-card="true"\],[\s\S]*?\[data-question-key\] > section,[\s\S]*?\[data-plan-review-key\] > section \{[\s\S]*?background:linear-gradient\(var\(--hd-theme-readable-surface\),var\(--hd-theme-readable-surface\)\),var\(--hd-theme-input\) !important;/u)
  assert.match(source, /\[data-question-key\] \[role="(?:group|radiogroup)"\] > div:has\(> div\[aria-hidden="true"\] \+ textarea\)/u)
  assert.match(source, /textarea::placeholder \{[\s\S]*?-webkit-text-fill-color:var\(--dsw-alias-label-secondary\) !important;/u)
  assert.match(source, /html\[data-hd-theme\]:not\(\[data-hd-theme="official"\]\)\[data-hd-wallpaper-kind="video"\][\s\S]*?\[data-question-key\] > section,[\s\S]*?backdrop-filter:none!important;/u)
  assert.doesNotMatch(source, /Mbwy4a_|uV2eYG_/u)
})
