const test = require('node:test')
const assert = require('node:assert/strict')
const path = require('node:path')
const { readFile } = require('node:fs/promises')

const mainFile = path.resolve(__dirname, '..', 'electron', 'main.cjs')

test('Electron system-network JSON fetch keeps the safe policy while tolerating Chromium redirect cancellation', async () => {
  const main = await readFile(mainFile, 'utf8')
  const start = main.indexOf('async function fetchJsonWithSystemNetwork')
  const end = main.indexOf('\nfunction componentUpdateBootstrapContext', start)
  assert.ok(start >= 0 && end > start)
  const source = main.slice(start, end)
  assert.match(source, /safeHttpsUpdateUrl\(url, '更新清单地址'\)/u)
  assert.match(source, /fetchWithSafeRedirects\(current/u)
  assert.match(source, /fetchImpl: net\.fetch/u)
  assert.match(source, /maxRedirects,/u)
  assert.match(source, /allowedHosts,/u)
  assert.doesNotMatch(source, /\['https:', 'http:'\]/u)
})
