const test = require('node:test')
const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const path = require('node:path')

const root = path.join(__dirname, '..')
const read = file => readFileSync(path.join(root, file), 'utf8')

test('wallpaper library renders managed image and video previews as direct-use cards', () => {
  const html = read('renderer/index.html')
  const app = read('renderer/app.js')
  const styles = read('renderer/styles.css')

  assert.match(html, /class="skin-wallpaper-workbench"/)
  assert.match(html, /导入后会立即显示预览卡片/)
  assert.match(app, /<img data-wallpaper-preview src="\$\{escapeHtml\(item\.previewUrl\)\}"/)
  assert.match(app, /<video data-wallpaper-preview data-preview-src="\$\{escapeHtml\(item\.previewUrl\)\}" preload="none" muted loop playsinline/)
  assert.doesNotMatch(app, /<video data-wallpaper-preview[^>]*\ssrc=/)
  assert.doesNotMatch(app, /<video data-wallpaper-preview[^>]*autoplay/)
  assert.match(app, /card\.addEventListener\('pointerenter', \(\) => playWallpaperCardPreview\(card\)\)/)
  assert.match(app, /card\.addEventListener\('pointerleave', \(\) => pauseWallpaperCardPreview\(card\)\)/)
  assert.match(app, /matchMedia\('\(prefers-reduced-motion: reduce\)'\)/)
  assert.match(app, /disposeWallpaperCardPreviews\(video\)/)
  assert.match(app, /video\.src = source\s+video\.load\(\)/)
  assert.match(app, /function disposeWallpaperCardPreview\(video\)[\s\S]*?video\.pause\(\)[\s\S]*?video\.removeAttribute\('src'\)[\s\S]*?video\.load\(\)/u)
  assert.match(app, /function closeSkinPicker\(\) \{\s*disposeWallpaperCardPreviews\(\)\s*skinPickerHost\.close\(\)/u)
  assert.match(app, /disposeWallpaperCardPreviews\(\)\s*skinWallpaperLibraryItems\.innerHTML = items\.map/u)
  assert.match(app, /current \? '正在使用' : '使用此壁纸'/)
  assert.match(app, /card\.addEventListener\('dblclick'/)
  assert.match(styles, /\.skin-wallpaper-library-preview img,\.skin-wallpaper-library-preview video \{[^}]*object-fit:cover/u)
})

test('wallpaper transparency controls are visible draggable sliders with live preview and release-time persistence', () => {
  const html = read('renderer/index.html')
  const app = read('renderer/app.js')
  const styles = read('renderer/styles.css')
  const guest = read('renderer/theme-integration.js')

  assert.match(html, /id="skinGlassTransparency" type="range" min="0" max="100" step="1"/)
  assert.match(html, /将文字保护调到 0 时不会再强制增加遮罩/)
  assert.match(styles, /input\[type="range"\]::-webkit-slider-runnable-track/)
  assert.match(styles, /input\[type="range"\]::-webkit-slider-thumb/)
  assert.match(app, /input\.addEventListener\('input',[\s\S]*previewWallpaperAppearance\(name, Number\(input\.value\)\)/u)
  assert.match(app, /input\.addEventListener\('change', \(\) => persistWallpaperAppearance\(\)/)
  assert.match(app, /requestAnimationFrame\([\s\S]*publishAppearanceState\(\)/u)
  assert.match(html, /id="skinResetWallpaperAppearance"[^>]*>恢复推荐参数<\/button>/)
  assert.match(app, /skinResetWallpaperAppearance\.addEventListener\('click'/)
  assert.match(app, /recommended\[name\] = customThemeDefaults\[name\]/)
  assert.match(app, /customTheme: \{ \.\.\.\(appearanceState\.customTheme \|\| \{\}\), \.\.\.recommended \}/)
  assert.match(app, /已恢复推荐显示参数并保存；当前壁纸和主题配色保持不变。/)
  assert.match(guest, /glassTransparency: boundedNumber\(custom\.glassTransparency, 0, 100, 32\)/)
  assert.match(guest, /const surfaceOpacity = 1 - custom\.glassTransparency \/ 100/)
  assert.match(guest, /wallpaperOverlay: hexWithOpacity\(surface, readability \*/)
  assert.doesNotMatch(guest, /max="92"/)
})

test('Wallpaper Engine primary action imports one current project while browsing remains read-only', () => {
  const html = read('renderer/index.html')
  const app = read('renderer/app.js')
  const main = read('electron/main.cjs')

  assert.match(html, /id="skinChooseWallpaperEngine"[^>]*>导入当前 Wallpaper Engine 壁纸<\/button>/)
  assert.match(html, /id="skinBrowseWallpaperEngine"[^>]*>浏览 Wallpaper Engine 壁纸…<\/button>/)
  assert.match(app, /skinChooseWallpaperEngineButton\.addEventListener\('click', \(\) => importCurrentWallpaperEngineProject\(\)\)/)
  assert.match(app, /skinBrowseWallpaperEngineButton\.addEventListener\('click', openWallpaperEnginePicker\)/)
  assert.match(app, />选择并使用<\/button>/)
  assert.doesNotMatch(app, />导入并使用<\/button>/)
  assert.match(main, /current\.projects\.length === 1/)
  assert.match(main, /status: 'selection-required'/)
  assert.match(main, /projects\.length > 1\s*\? 'multiple-current'/)
})
