# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Baiyuscc13724Max.HarnessDesktop
PackageVersion: 1.0.14
InstallerType: inno
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
ProductCode: '{A116521E-7A92-4B10-9F64-315E8ED7A499}_is1'
AppsAndFeaturesEntries:
  - DisplayName: Harness Desktop
    Publisher: Harness Desktop Contributors
    DisplayVersion: 1.0.14
    ProductCode: '{A116521E-7A92-4B10-9F64-315E8ED7A499}_is1'
    InstallerType: inno
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/baiyuscc13724-max/deepseek-harness-desktop-releases/releases/download/v1.0.14/Harness-Desktop-1.0.14-win-x64.exe
    InstallerSha256: 0FBD0F423C966F567A736BFE436B651BB9A9F4B20C0BC0884BC709015363911B
ManifestType: installer
ManifestVersion: 1.12.0
